spr_c_UP  =$2; unused
spr_c_DOWN  =$3; unused
snd_c_FILTER_HIGHPASS  =$40
quads_s_add_textures  =$7b0e
ball_v_spin_type  =$2639
golfer_s_update1_powering_up  =$41ee; ?
playmsg_l_ADJ_OFFSETS  =$57ed
quads_check_minmax_x  =$7911; ?
LINE_X1_LO  =$2b
bdrop_s_deactivate_sprites  =$2347; ?
ball_vy_hi  =$25f0
stats_l_UNITS_TEXT  =$a006; ?
GOLFER_POS_MARKER_MAX_X  =$e8; unused
hole_c_OVERHEAD_BALL_PTR  =$5c
sfx_l_BIRD1_DATA  =$89d8
trees_v_color_code_totals  =$af15
stats_s_clear  =$a1c5
SP5COL  =$d02c; unused
ORANGE  =$8
ball_x_hi  =$25e5
round_current_gender_offset  =$8192; unused
trees_v_proj_x  =$af0c
spr_s_clear_all_expands  =$f84; unused
ball_c_PUTTING_MIN_VZ  =$70
powarc_l_POWER_REDUCTIONS  =$5fe1; ?
interrupts_c_BOTTOM  =$3
tmarkers_c_PATTERN  =$a387
hole_c_PULSE_COLORS_N  =$6
trees_v_proj_y  =$af0d
slope_v_vz_hi  =$24b3
ball_c_MUTEX_READY  =$0; unused
trees_c_DIST_N  =$a
winslp_c_BEGIN  =$b97e
ball_v_mc_y  =$2635
quads_add_point_to_buffer  =$7250; ?
shared_v_team_names_offsets_begin  =$16b7
golfer_c_STATE_PRECISION  =$4
ball_vy_lo  =$25ef
ball_v_mc_x  =$2634
terrain_l_NUM_CHARS_TO_PAINT  =$a3f2
R6510  =$1
ball_c_MAX_PUTTING_SPEED  =$1
ball_x_lo  =$25e4
bdrop_c_MAX_DISTANT_OBJECTS  =$5
powarc_s_draw_max_animation  =$63cf; ?
trees_v_row0  =$af10
trees_s_select_depth_index  =$b0fa; ?
slope_v_vz_lo  =$24b2
ball_c_SPIN_TYPE_HOOK  =$1
quads_clip_x  =$7665; ?
SPENA  =$d015
ball_v_spin_x_hi  =$2613; unused
CAMERA_HORIZON  =$80; unused
maths_l_TRIG_BASE_I  =$4fa0
stats_l_STRING_MEM_FINAL_SHOT_OFFSET  =$a01e
POWARC_POWER_STEPS_DATA  =$588c
font_s_draw_text_direct  =$1a7c; unused
FS0  =$189; unused
RASTER  =$d012
shared_c_PLAYING_FRONT_9  =$1; unused
font_s_draw_text  =$1a5a
ball_c_SW_SPR_NUM  =$5
golfer_v_direction_z_hi  =$3c83
sstore_c_DATA_PUTT_LOWER_MALE  =$9c06
golfer_v_punch_selected  =$3c8f; ?
sfx_l_BROWSE_INIT  =$8909
FS1  =$313; unused
spr_s_hide_all  =$f8f; unused
font_c_ASCII_SPACE  =$20
interrupts_s_restore_zp  =$49f1
sc_v_scores_end  =$86de
stats_l_BALLS_HOLED_PATTERNS  =$a024
golfer_s_init_marker_move  =$4374; ?
target_c_SIZE  =$41e; unused
round_s_init_screen_wipe  =$85e0; ?
FS2  =$627; unused
CB_LOADFILE_EXOMIZER  =$5c5
GOLFER_POS_X_LO  =$8c
round_v_current_distance_hi  =$81a1
trees_v_rot_x_hi  =$a919
sprd_c_GOLFER_PUTT_LOWER  =$69; unused
round_s_loop  =$828f; ?
sstore_l_DST_LO  =$9f56
sfx_l_SPLASH_INIT  =$898b
FS3  =$c4e; unused
SPSPCL  =$d01e; unused
VCREG2  =$d40b; unused
msg_c_LOADING_SCORE_CARDS  =$1
bdrop_v_pattern_indices  =$21f3
partsys_l_COLORS  =$5419
sstore_c_SHOT_TYPE_SWING_MALE  =$0
round_s_check_if_shot_complete  =$8512; ?
ball_v_spin_x_lo  =$2612
ball_s_check_trunk_deflection  =$3548; ?
powarc_c_MAX_SPR_Y  =$ce
target_s_update_hole_color  =$7fef; ?
clubs_s_prev  =$3aa3
wind_c_SIZE  =$113; unused
FS4  =$189c; unused
VCREG3  =$d412; unused
SCR_CODE_BANG  =$21
golfer_v_direction_z_lo  =$3c82
powarc_c_MAX_SPR_X  =$43
target_s_draw  =$7d49
wash_c_SIZE  =$63; unused
FS5  =$3138; unused
ZP_END  =$6c
spr_v_color  =$d7e
ball_v_current_terrain  =$2652
playmsg_v_last_index  =$5804
ball_v_mutex_vz_lo_on_bounce  =$265b
golfer_update1_putt_power  =$4094; unused
partsys_c_BEGIN  =$537c
spr_v_is_next_frame  =$dd0
ball_s_update_overhead_ball  =$36c4; ?
target_l_FABRIC_PATTERN_OFFSETS  =$7c2c
FS6  =$6271; unused
VCREG1  =$d404; unused
bdrop_l_AVAILABLE_SW_SPRITES  =$1f2a
ball_v_mutex_vz_hi_on_bounce  =$265c
GOLFER_POS_X_HI  =$0; unused
PRODUCT  =$6
GOLFER_CLUB_HIGHLIGHT_COLOR  =$b; unused
round_v_current_distance_lo  =$81a0; ?
sstore_l_DST_HI  =$9f5e
trees_v_rot_x_lo  =$a8c9
FS7  =$c4e3
sstore_c_SWING_UPPER_FEMALE  =$2
ZSIN_LO  =$18; unused
hole_s_update_pulse  =$482e; ?
PUTT_ASSIST_DEST_ZP_HI  =$5f
ball_colors  =$264c; unused
GOLFER_UPPER_BODY_SPR_NUM  =$2
partsys_g_hi  =$5467
playmsg_v_buffer  =$57f7
quads_num_vertices  =$6620
sfx_c_BALL_CLUB  =$3; ?
B1  =$41b; unused
D2  =$4e2; unused
F3  =$b9d; unused
LINE_Y1_LO  =$2c
dp_s_draw_pixel  =$136f
gfxs_s_init  =$b2e; unused
spr_c_LEFT  =$0
shared_v_is_match_play  =$16c2
ball_s_do_final_terrain_check  =$37be
bdrop_v_spr_ptr_from  =$2207
playmsg_c_SHOT_TYPE_STR  =$5798
quads_solve_linear  =$727d; ?
B0  =$20d; unused
F2  =$5ce; unused
D3  =$9c4; unused
spr_v_dx  =$d5e; unused
golfer_c_BASE_DIRECTION_X_LO  =$0
interrupts_c_SIZE  =$1d4; unused
ball_s_check_bounds  =$3360; ?
quads_v_vram_addrs_lo  =$6f28
players_v_current_shots  =$5664; ?
D0  =$138; unused
F1  =$2e7; unused
B3  =$106c; unused
app_s_run_prelude  =$c20; unused
spr_v_dy  =$d6e; unused
shared_v_team_membership  =$16bb
CAMERA_MAX_VALID_Z_HI  =$c; ?
golfer_l_MARKER_BOUNDS  =$3bf3
GOLFER_PUTT_POWER_INCREMENT  =$8
ingm_c_SIZE  =$124; unused
sfx_l_BALL_CUP_DATA  =$897c
end_of_play  =$bd8c; unused
ball_mutex_x_hi  =$25fb; unused
target_z_lo  =$7c53; ?
quads_buf2_min_z_hi  =$6ea5
F0  =$173; unused
D1  =$271; unused
B2  =$836; unused
BIT_ZEROPAGE  =$24
golfer_anim_frame  =$3c7e
playmsg_c_ADJECTIVE_STR  =$5782
ZSIN_HI  =$19; unused
sfx_c_BOUNCE  =$1; ?
PUTT_ASSIST_DEST_ZP_LO  =$5e
hole_c_PIXELS_PER_YARD  =$15; ?
clubs_c_PW  =$a; unused
partsys_g_lo  =$5466
B5  =$41b4; unused
D6  =$4e22; unused
F7  =$b9d6
bdrop_v_spr_framerate  =$2211
stats_l_PAR_HIGHLIGHT_OFFSETS  =$a01c
winslp_s_rotate  =$ba83; ?
round_s_check_if_hole_complete  =$83ba; ?
B4  =$20d9; unused
F6  =$5ceb; unused
D7  =$9c45
joy_c_UP  =$1
font_c_ASCII_MINUS  =$2d
ball_v_mutex_vy_lo_on_bounce  =$2659
golfer_c_BASE_DIRECTION_X_HI  =$0
ingm_c_BEGIN  =$4859
sfx_l_BOUNCE_DATA  =$892b
quads_v_vram_addrs_hi  =$6f68
D4  =$1388; unused
F5  =$2e75; unused
B7  =$ffd0; unused
MSIGX  =$d010; unused
bdrop_v_golfer_angle  =$2235
golfer_s_draw_lower  =$3cb3
BLACK  =$0
shared_v_wind_difficulty  =$16c6
CAMERA_MAX_VALID_Z_LO  =$4e; ?
powarc_l_POWER_UP_FRAME_RATES  =$607d
ball_v_mutex_vy_hi_on_bounce  =$265a
ball_s_update_in_flight  =$2999
round_s_init_hole  =$8277
ball_mutex_x_lo  =$25fa; unused
target_z_hi  =$7c54; ?
quads_buf2_min_z_lo  =$6ea4
F4  =$173a; unused
D5  =$2711; unused
B6  =$8368; unused
P0  =$2
XSIN_LO  =$14; unused
SND_CH3_DATA_ZP_LO  =$52; unused
clubs_l_PUNCH_VY_LO  =$39ec; unused
TARGET_SPR_Y_OFFSET  =$14
sstore_c_DATA_PUTT_LOWER_FEMALE  =$9f06
maths_s_rotate_vec_to_pos_z_axis  =$533a; ?
round_v_allow_water  =$819f; ?
players_c_MALE  =$0; unused
P1  =$3
SCR_CODE_OPEN_BRACKET  =$1b; unused
ball_l_SPIN_AXIS_Z_LO  =$255f
target_c_DATA_PTR  =$30
wash_c_BEGIN  =$bcc2
wash_c_FRAME_RATE  =$2
sfx_l_BIRD2_DATA  =$89ec
trees_v_trunk_heights  =$a4c5
partsys_s_clear_sprite  =$5605; ?
P2  =$4
CURSOR_POS_SR_HI  =$4d; unused
SCR_CODE_HUH  =$3f; unused
shared_v_sand_traps_difficulty  =$16c4
snd_s_next_free_channel  =$1d0f; unused
powarc_c_POWER_UP_SPEED_NORMAL  =$0
target_l_DIST_HI  =$7bf2
round_s_order_players  =$832a; ?
P3  =$5
bdrop_s_update  =$23c8
slope_v_quadrant  =$24b4; unused
partsys_c_SPR_NUM  =$4; ?
winslp_v_rot_vx_hi  =$ba38; ?
clubs_c_DR  =$0
P4  =$6
XSIN_HI  =$15; unused
SND_CH3_DATA_ZP_HI  =$53; unused
interrupts_s_copy_zp  =$49e5
clubs_l_PUNCH_VY_HI  =$39f9; unused
shared_l_PLAYER_SHIRT_COLORS  =$1633
powarc_c_PUTT_ASSIST_NUM_COLORS  =$6
spr_s_animate_pingpong  =$2443; ?
ball_v_force_target_redraw  =$263e
ball_s_update_roll  =$2add
golfer_init_watching_shot1  =$3ef1
P5  =$7
slope_s_init  =$24d1
BALL_TREE_COLLISION_STATE_ACTIVE  =$1
ball_l_SPIN_AXIS_Z_HI  =$2570
round_c_MSG_CUT_SHORT  =$1; ?
clubs_v_min_allowed  =$3a88
golfer_c_STATE_READY  =$0
EXTCOL  =$d020
P6  =$8
CURSOR_POS_SR_LO  =$4c
ball_v_mutex_vx_lo_on_bounce  =$2657
hole_v_overhead_map_icon  =$4646
target_l_DIST_LO  =$7bea
P7  =$9
bdrop_v_spr_y  =$21f8
ball_v_mutex_vx_hi_on_bounce  =$2658
golfer_c_STATE_ANIMATE_FORESWING  =$8
stats_s_draw_name  =$a1d4; ?
winslp_v_rot_vx_lo  =$ba37; ?
ball_s_update_time_critical  =$2c33
target_s_prepare_hole_sprite  =$7f16; ?
stats_s_refresh_balls_holed_markers  =$a323
spr_v_direction_x  =$cde; unused
bdrop_c_SIZE  =$604; unused
ball_l_FRICTION_COEFFICIENTS  =$2586
ball_v_vy_lo_on_bounce  =$265f
tmarkers_c_VRAM_DEST0  =$cb7d
maths_div16  =$4fa8; ?
quads_max_y_point  =$6af3
stats_s_draw_holes_to_play  =$a2ce; ?
quads_drawing_order  =$6d4c
stats_s_refresh_hole  =$a108; ?
COLOR_RAM  =$d800
LINE_X0_LO  =$29
ball_v_vy_hi_on_bounce  =$2660
tmarkers_c_VRAM_DEST1  =$cb8a
powarc_c_SLOW_MARKER_NUM_BYTES  =$6
SCR_CODE_AT  =$0; unused
quads_triangles_z_intercept_hi  =$6e78; ?
spr_v_direction_y  =$cee; unused
sfx_l_BALL_CLUB_INIT  =$895a
EDGES_LO  =$2d
ball_vx_hi  =$25ee
playmsg_c_ALERT_STR  =$57c1
sc_v_score_str_buffer  =$86de
SP4COL  =$d02b; unused
HIBASE  =$288; unused
SCR_CODE_GT  =$3e; unused
ball_y_hi  =$25eb
powarc_v_max_anim_frame_count  =$61bc
winslp_v_count  =$ba40
SHFLAG  =$28d; unused
sprd_c_GOLFER_WATCHING_SWING_UPPER  =$6d
GOLFER_PUTT_CLUB_SHAFT_OFFSETS_Y  =$d6
GOLFER_CLUB_X  =$3c21
golfer_v_current_response  =$3c8b
hole_s_draw_overhead_ball  =$4812
LIGHT_BLUE  =$e
spr_c_VISIBLE_ALL_T  =$32
BALL_SHADOW_HEIGHTS_LO  =$2537
clubs_c_OFFSET_TO_PUNCH_VELOCITIES  =$34; ?
GOLFER_CLUB_Y  =$3c2f
GOLFER_PUTT_CLUB_SHAFT_OFFSETS_X  =$ae
golfer_s_update_looking_down  =$40e7; ?
partsys_c_SIZE  =$2d0; unused
end_of_core  =$1e6c
ball_c_LIE_STRING_LEN  =$a
snd_s_update  =$1d9c
playmsg_c_TYPE_PUTT  =$5; ?
partsys_s_draw  =$563e; ?
EDGES_HI  =$2e
utils_s_16bit_hex_to_dec  =$a7c
gfxs_c_BITMAP_OFFSET  =$8; unused
spr_c_VISIBLE_ALL_R  =$40; unused
quads_triangles_z_intercept_lo  =$6e5f; ?
golfer_v_marker_move_count  =$3c85
bdrop_v_current_position  =$2234
GOLFER_FRAMES_TO_CONTACT  =$1c
ball_vx_lo  =$25ed
ball_s_draw_shadow  =$2dff; ?
sprd_c_GOLFER_PUTT_FORESWING_FRAMES_PT1  =$3; unused
ball_y_lo  =$25ea
tweeter_v_is_on  =$bd28
ball_l_SPR_DATA_ODD_ROW1  =$259a; unused
playmsg_c_TYPE_DOUBLE_BOGEY  =$0; unused
golfer_v_is_hidden  =$3c86
playmsg_s_display_alert  =$5864
powarc_l_MAX_ANIM_COLOR_CYCLE  =$6006
SETLFS  =$ffba; unused
sprd_c_GOLFER_PUTT_FORESWING_FRAMES_PT0  =$4
sprd_c_GOLFER_CONTACT_OFFSET  =$9
ball_l_SPR_DATA_ODD_ROW0  =$2596; unused
BALL_SHADOW_HEIGHTS_HI  =$253a
sstore_v_last_sequence  =$9f6e
font_c_ASCII_0  =$30
ball_v_vx_lo_on_bounce  =$265d
ball_v_spin_y_hi  =$2615; unused
target_coll_upper_z_lo  =$7c58
hole_v_boundary_aa_bottom_lo  =$4642; ?
slope_v_index  =$24b5
hole_current_rotation_quadrants  =$4644
ball_v_vx_hi_on_bounce  =$265e; unused
partsys_v_OFFSCREEN_BUFFER  =$537c
hole_v_overhead_ball_y  =$473d; ?
pythag_c_BEGIN  =$64c1
VIOLET  =$4
SCR_CODE_SEMICOLON  =$3b; unused
POWARC_PRECISION_STEPS_DATA  =$5b4b
wind_l_RANDOM_ADDENDS  =$b86e
ball_s_calc_spin  =$31a2; ?
CAMERA_HALF_SCREEN_WIDTH_HI  =$0
powarc_v_precision_ended  =$6097; ?
KB_MATRIX_DECODE_TBL  =$eb81; unused
bdrop_v_repeating_pattern_addr_lo  =$20c2
ball_c_SPLASH_ANIM_FRAME_RATE  =$4
trees_v_temp_in_front_of_target  =$af14
interrupts_c_LOWER_MIDDLE  =$2; unused
powarc_c_PUTT_ASSIST_FRAME_RATE  =$4
partsys_s_deactivate  =$5646
gfxs_s_clear_msg_area  =$b9c
spr_s_animate_onetime  =$e7b
golfer_c_STATE_ANIMATE_FORESWING_PUTT  =$d
msg_s_clear  =$1c9f
GOLFER_LOWER_BODY_POS_X  =$3c13
quads_max_z_point  =$6aef
trees_s_compare  =$b075; ?
trees_s_determine_color_code_for_trunk  =$b3de; ?
snd_c_OSC_OFF_CMD  =$fd; unused
rand_s_get  =$8132; ?
ball_v_spin_y_lo  =$2614; unused
target_coll_upper_z_hi  =$7c59
hole_v_boundary_aa_bottom_hi  =$4643; ?
powarc_c_POWER_UP_SPEED_SLOW  =$1; unused
quads_prepare_for_projection  =$714c
sfx_c_BALL_CUP  =$4; ?
golfer_s_check_punch_toggle  =$459c; ?
golfer_s_record_distance2  =$45f8
GOLFER_HOLD_TIME  =$6
app_s_run  =$c02; unused
utils_s_bubble_sort  =$acf
gfxs_c_CHARS_TO  =$c000; unused
quads_triangle_indices  =$6dfb; ?
target_s_project  =$7d81
BALL_TREE_COLLISION_STATE_NONE  =$0; unused
ball_v_z_pos_rel_to_hole_new  =$266b
CAMERA_HALF_SCREEN_WIDTH_LO  =$a0
SCR_CODE_UP  =$1e; unused
bdrop_v_repeating_pattern_addr_hi  =$20c3
powarc_s_update  =$61c4; ?
BALL_SHADOW_COLORS  =$2533
ball_s_set_direction_vector  =$2792
interrupts_s_do_shot_in_progress  =$4a39; ?
joy_c_RIGHT  =$8
shared_v_player_joysticks  =$1681
utils_l_EOR_BIT_LOOKUP  =$a6e
ball_c_BEGIN  =$2527
hole_v_boundary_aa_left_lo  =$463e; ?
GOLFER_BACKSWING_FRAME_RATE  =$7
powarc_c_PUTT_ASSIST_NUM_STEPS  =$6
LINE_Y0_LO  =$2a
SCR_CODE_SPACE  =$20
DIVIDEND  =$2
spr_s_move_right  =$dee; unused
ball_v_collision_type  =$262d
quads_z_lo  =$6702
quads_v_shimmers_n  =$7028
msg_s_display  =$1c6a
msg_s_display_at_column  =$1c71; unused
quads_min_y_point  =$6af2
sfx_c_SWISH  =$2; ?
powarc_c_MAX_HW_SPR_NUM  =$6
trees_s_set_aa_coords  =$af77; ?
sstore_c_DATA_SWING_UPPER_MALE  =$8a46
golfer_s_update1_finished  =$4065; ?
golfer_c_STATE_ANIMATE_BACKSWING  =$6
golfer_v_current_skin_tone  =$3c8a
quads_buf2_z_lo  =$6e9a
quads_min_z_hi  =$6aeb; unused
ball_c_TERRAIN_GREEN_FWAY  =$2
ball_mutex_y_hi  =$25ff
ball_v_drag_z_hi  =$260b
golfer_s_handle_concede_response  =$44ee
tweeter_c_BEGIN  =$bd25
sprd_c_PARTICLES_SHOT  =$31
maths_s_restore_std_trig  =$52f9; ?
hole_v_boundary_aa_left_hi  =$463f; ?
quads_compare  =$78b5
waypts_n  =$b737
spr_c_VISIBLE_ALL_B  =$e5; unused
snd_v_counter  =$1cd3; unused
round_c_STATE_SHOT_COMPLETE  =$1; ?
interrupts_s_install  =$49af
hole_v_overhead_ball_active  =$473e
quads_z_hi  =$6766
slope_s_rotate  =$24b6
sfx_l_SWISH_DATA  =$8942
DIVISOR  =$4
round_v_current_tee_index  =$818e
quads_l_TEXTURE_COLOR_OFFSETS  =$6609
ball_c_PUTT_TOO_FAST  =$2
ball_v_drag_z_lo  =$260a
caddie_c_BEGIN  =$3862
GOLFER_CROSSHAIR_SPR_NUM  =$6
clubs_l_DISTANCE_STR  =$3a20
quads_min_z_lo  =$6aea; unused
quads_buf2_z_hi  =$6e9e
quads_l_SHIMMER_PATTERNS  =$6617
ball_mutex_y_lo  =$25fe
sfx_l_INIT_ADDRS  =$8a0d
winslp_c_SIZE  =$2a7; unused
FREHI1  =$d401; unused
FRELO3  =$d40e; unused
SND_CH2_DATA_ZP_LO  =$50; unused
ball_v_vz_lo_on_bounce  =$2661; unused
powarc_v_putt_assist_index  =$61c0; ?
ball_c_SHADOW_SPR_ADDRESS  =$cd00
hole_c_PULSE_FRAME_RATE  =$a
pythag_v_speed_squared_lo  =$6541; unused
quads_c_SCREEN_HEIGHT  =$c8
wind_l_MULTIPLIERS_LO  =$b889
quads_rot_min_z_lo  =$6d65; unused
BIT_ABSOLUTE  =$2c
ball_v_vz_hi_on_bounce  =$2662; unused
powarc_c_MAX_SPR_PTR  =$5d
golfer_s_update0_hold_animate  =$42c8; ?
target_l_FABRIC_PATTERN_OFFSETS_END  =$7c34
FRELO2  =$d407; unused
ball_s_apply_spin  =$3176; ?
powarc_v_max_anim_iter  =$61bd
tmarkers_c_CRAM_VALUE  =$6
SETNAM  =$ffbd; unused
joy_v_fire_locked  =$9e5
quads_l_SHIMMER_COLORS  =$6614
quads_s_add_shimmer  =$7ae4
FRELO1  =$d400; unused
ball_v_last_in_front_of_trunk  =$2638
FREHI3  =$d40f; unused
target_l_POLE_HEIGHTS  =$7c03
FREHI2  =$d408; unused
spr_c_VISIBLE_ALL_L  =$18
golfer_s_init_shadow  =$4420
play_s_loop  =$1e6c; unused
ball_s_launch_putt  =$2abe
rand_c_BEGIN  =$7fff
tweeter_c_MIN_WAIT_TICKS  =$96
bdrop_v_spr_ptr_to  =$220c
SP4X  =$d008; unused
SP6Y  =$d00d; unused
SND_CH2_DATA_ZP_HI  =$51; unused
round_c_LOADING_MSG  =$815c
joy_v_right_locked  =$9e3
pythag_v_speed_squared_hi  =$6542; unused
ball_s_deflect  =$357c; ?
wind_l_MULTIPLIERS_HI  =$b890
quads_rot_min_z_hi  =$6d7e; unused
SP4Y  =$d009; unused
SP6X  =$d00c; unused
clubs_s_ghost_carry  =$3b4b
powarc_l_PUTT_ASSIST_STEP_MARKERS  =$600f
SP0X  =$d000; unused
SP2Y  =$d005; unused
SCR_CODE_OPEN_PAREN  =$28; unused
target_c_POLE_COLLISION_MIN_DEPTH  =$3; ?
fmag_c_BEGIN  =$4b51
quads_min_z_point  =$6aee; unused
partsys_color  =$5468
trees_l_LO_RES_PIXEL_MASKS  =$a4a3
clubs_c_BUFF_LEN  =$3
golfer_s_record_distance  =$3f15; unused
clubs_c_8I  =$8
SP0Y  =$d001
SP2X  =$d004; unused
GOLFER_STRIKE_FRAME  =$ae; unused
quads_find_all_minmax_z  =$78ec; ?
partsys_v_animating  =$546a
gfxs_c_CHARS_OFFSET  =$0; unused
GOLFER_UPPER_BODY_LOOKING_UP_POS_Y  =$c3
golfer_s_update_score_card  =$45c5
GOLFER_POS_Y_LOWER  =$d3; unused
WHITE  =$1
bdrop_c_PATTERN_BLOCK_SIZE  =$120
BALL_SHADOW_MAX_Y_HI  =$0; ?; unused
ball_v_is_in_hole  =$262e
sstore_l_SRC_LO  =$9f46
rand_v_iter  =$80ff
SP7COL  =$d02e; unused
app_s_run_finale  =$c43; unused
ball_z_hi  =$25e8
powarc_c_SLOW_MARKER_DESTINATION  =$fbc9
golfer_l_RESPONSE_OFFSET_BEGIN  =$3c71
slope_c_BEGIN  =$2480
powarc_v_precision_delay_hi  =$61b9
PARTSYS_HI  =$34
GOLFER_CLUB_NORMAL_COLOR  =$0
round_s_load_score_table  =$8597; ?
slope_v_vx_hi  =$24b1
ball_c_PHYSICS_VARIABLES_END  =$2628
golfer_advance_putting_animation  =$41c2; ?
hole_s_draw_overhead_map  =$47ce
trees_l_DIST_LO  =$a423
fmag_c_SIZE  =$24b; unused
bdrop_c_MAX_VISIBLE_DISTANT_OBJECTS  =$3; unused
quads_triangles_vertex_to_omit  =$6e14; ?
playmsg_c_BUFFER_LEN  =$d
round_s_set_bg_colors  =$8402; ?
SCR_CODE_CLOSE_BRACKET  =$1d; unused
ball_l_FRICTION_ON_BOUNCE  =$252f
ball_c_MUTEX_WANT_NEW  =$1
tweeter_s_update  =$bd29; ?
powarc_c_PUNCH_MARKER_DATA  =$608b; unused
sstore_l_SRC_HI  =$9f4e
BALL_SHADOW_MAX_Y_LO  =$38; ?; unused
ball_z_lo  =$25e7
golfer_s_move_marker  =$438a; ?
powarc_c_SLOW_MARKER_CLEAR_DATA  =$6085; unused
ball_s_execute_bounce  =$2a7a; ?
powarc_v_precision_delay_lo  =$61b8
PARTSYS_LO  =$33
slope_v_vx_lo  =$24b0
CLUBS_N  =$c
GOLFER_PRECISION_ZONE_START  =$16; unused
transtn_s_init  =$bc27; ?
trees_l_DIST_HI  =$a42d
stats_s_draw_distance  =$a055
SCROLY  =$d011
LIGHT_GREEN  =$d
sprd_c_PARTICLES_SPLASH  =$32; unused
round_v_current_state  =$818a; ?
powarc_s_display_clear_marker  =$649a; ?
sprd_c_GOLFER_SWING_UPPER  =$5f
ball_x_fraction  =$25e6
hole_v_boundary_aa_top_hi  =$463d; ?
waypts_find_index  =$b739; ?
ball_v_spin_z_hi  =$2617; unused
GS0  =$1ba; unused
CS1  =$24e; unused
SCROLX  =$d016; unused
bdrop_c_ANIM_LOOP  =$0; unused
ball_c_SPIN_TYPE_NONE  =$0
ball_s_check_tree_collision  =$2d84; ?
golfer_v_direction_x_hi  =$3c81
ball_z_fraction  =$25e9
snd_v_waiting_to_end  =$1ccd; unused
quads_c_VERTEX_STATE_OOB_RIGHT  =$2
rand_c_SIZE  =$15d; unused
CS0  =$126; unused
GS1  =$373; unused
shared_l_NAME_ADDR_HI  =$1642
players_c_MAX_N  =$4
tmarkers_c_SHADOW_BASE_DEST0  =$fbe6
target_s_align_mask_bytes  =$7f80; ?
sfx_s_init  =$8a35; ?
round_s_handle_request_next_shot  =$82df; ?
round_c_SIZE  =$4f8; unused
GS2  =$6e8; unused
CS3  =$937; unused
CINV  =$314
TREES_LO  =$1b
ball_v_current_ground_speed  =$2621; unused
quads_wbuf_size  =$6d4b
tmarkers_c_SHADOW_BASE_DEST1  =$fd20
trees_v_rot_z_hi  =$a9b9
BITMAP_LO  =$21
clubs_s_draw_distance  =$3ae2; ?
powarc_l_PUTT_ASSIST_STEP_MARKER_OFFSETS  =$606c
CS2  =$49c; unused
GS3  =$dcf; unused
SCR_CODE_DASH  =$2d; unused
ball_v_spin_z_lo  =$2616
hole_v_boundary_aa_top_lo  =$463c; ?
golfer_s_update_looking_up  =$40b9; ?
stats_l_PAR_STR_ENDS  =$a016
target_l_WIDTHS  =$7c0c
interrupts_c_REQUEST_NONE  =$ff
interrupts_c_UPPER_MIDDLE  =$0; unused
playmsg_c_TYPE_EAGLE  =$4; unused
target_v_foliage_masks_offset  =$7c61
GS4  =$1b9f; unused
CS5  =$24e0; unused
shared_c_NUM_COURSES  =$6; unused
golfer_v_direction_x_lo  =$3c80; ?
ball_l_SPR_DATA_SMALL  =$25ae; unused
golfer_c_STATE_ANIMATE_BACKSWING_PUTT  =$b
hole_c_ICON_NUM_BYTES  =$f5
snd_c_NUM_CHANNELS  =$3; unused
ball_s_undo_rotation  =$2931
golfer_s_update0_hold  =$4223; ?
trees_s_draw_tile  =$b1a4; ?
golfer_c_RESPONSE_GHOST_COLOR  =$b
CS4  =$126f; unused
GS5  =$373f; unused
SCNKEY  =$ff9f
shared_l_NAME_ADDR_LO  =$163e
msg_c_FISHING  =$2
quads_c_NUM_SHIMMER_COLORS  =$3
ball_c_STATE_STATIONARY  =$0
powarc_v_putt_assist_is_active  =$61c2
stats_s_inc_balls_holed  =$a363; ?
GS6  =$6e7f; unused
CS7  =$937f; unused
TREES_HI  =$1c
SCR_CODE_CLOSE_PAREN  =$29; unused
round_v_must_retake_shot  =$8191
trees_v_rot_z_lo  =$a969
joy_s_is_vertical  =$9f6; unused
BITMAP_HI  =$22
ball_c_TERRAIN_BUNKER  =$1
ball_c_NUM_SHADOW_COLORS  =$4
stats_v_string_mem  =$a03f
CS6  =$49bf; unused
GS7  =$dcff; unused
golfer_v_crosshair_active  =$3c7d
wash_s_update  =$bce2; ?
pythag_l_SQUARES_LO  =$64c1
round_s_check_score_cards_exit  =$85c3; ?
msg_l_MSG_ADDR_HI  =$1c5f; unused
powarc_v_power_offset  =$6094; ?
hole_v_overhead_origin_y  =$4639; ?
CAMERA_MIN_VALID_Z_HI  =$ff
caddie_c_SIZE  =$0; unused
quads_c_MAX_VALID_X_PLUS_ONE_LO  =$a0
round_s_prepare_for_shot  =$84c1; ?
shared_c_PLAYING_BACK_9  =$2; unused
ball_reset  =$27f3; unused
golfer_c_BASE_DIRECTION_Z_LO  =$ff
hole_s_set_aa_boundaries  =$475f
quads_set_aa_coords  =$7564
sc_v_back9_scores  =$86da; unused
ZCOS_LO  =$16; unused
spr_v_vx_count  =$cbe; unused
ball_mutex_z_hi  =$25fd
ball_v_drag_y_hi  =$2609; unused
wind_c_INDICATOR_BYTES  =$b871
golfer_s_init_putt_animation  =$42dc; ?
target_x_lo  =$7c51
trees_c_MAX_N  =$50
round_s_set_joystick  =$83f8; ?
joy_v_current_port  =$9e7
pythag_l_SQUARES_HI  =$6501
trees_v_drawing_order  =$aa09
players_v_terrain  =$5678; ?
msg_c_ROW  =$c0; unused
msg_l_MSG_ADDR_LO  =$1c5a; unused
powarc_c_FULL_POWER_OFFSET  =$1f; ?
partsys_s_start  =$5621; ?
pythag_c_DRAG_COEFFICIENT  =$40; unused
wind_c_ARROW_LEN  =$60; unused
wind_c_INDICATOR_DEST  =$f7cc
CAMERA_MIN_VALID_Z_LO  =$e2
ttrunks_v_y0  =$b66c; ?
tweeter_s_reset  =$bd70; ?
quads_c_MAX_VALID_X_PLUS_ONE_HI  =$0
sstore_c_SWING_UPPER_MALE  =$0
ball_s_apply_drag  =$2fff; ?
golfer_c_BASE_DIRECTION_Z_HI  =$0
ZCOS_HI  =$17; unused
spr_v_vy_count  =$cce; unused
shared_v_holes  =$16c3
ball_mutex_z_lo  =$25fc
ball_v_drag_y_lo  =$2608; unused
ball_update_on_xz_plane  =$294d
quads_min_y_lo  =$6af0
target_x_hi  =$7c52
BROWN  =$9
SND_CH1_DATA_ZP_LO  =$4e; unused
app_s_run_play  =$c2d; unused
dp_l_BITMAP_ROWS_LO  =$fa0
stop_here  =$554e; unused
trees_c_MAX_DISTANCE_HI  =$10; ?
ball_s_draw  =$26e4; ?
target_rotate  =$7e3c
golfer_c_STATE_ANIMATE_HOLD_PUTT  =$c
font_c_ASCII_A  =$41; unused
bdrop_c_MAX_TILES  =$30
ball_l_SPIN_AXIS_X_LO  =$253d
ball_l_COLLISION_ODD  =$259e; unused
tweeter_c_SIZE  =$67; unused
powarc_s_draw_dummy  =$64a7
sstore_c_SHOT_TYPE_SWING_FEMALE  =$2
INTERRUPTS_LO  =$3f
dp_s_set_color_ram_cell  =$156a; unused
GOLFER_UPPER_BODY_POS_X  =$3bf7
dp_l_BYTE_PATTERNS  =$1284; unused
wash_v_frame_count  =$bcc8
sstore_c_PUTT_UPPER_MALE  =$4
trees_s_draw_shadow  =$b3a0; ?
quads_wbuf  =$6d2e
_DEBUG_TEST_HOLE_  =$0
XCOS_LO  =$12; unused
powarc_l_PUTT_ASSIST_COLORS  =$6072
shared_l_PLAYER_SKIN_TONES  =$162f
GOLFER_UPPER_BODY_POS_Y  =$3c05
golfer_s_evaluate_hole  =$447c; ?
REMAINDER  =$6
winslp_v_rot_vz_hi  =$ba3a; ?
shared_v_team_lens  =$16bf
bdrop_s_rotate_objects  =$242b
ball_s_check_collision_type  =$2bc8; ?
powarc_s_init_precision  =$634d; ?
interrupts_v_current_raster  =$4982
SND_CH1_DATA_ZP_HI  =$4f; unused
dp_l_BITMAP_ROWS_HI  =$1068
players_c_FEMALE  =$1; unused
trees_c_MAX_DISTANCE_LO  =$68; ?
shared_c_MAX_NAME_LEN  =$a
target_c_SW_SPR_NUM  =$7; ?
LIGHT_RED  =$a
ball_l_SPIN_AXIS_X_HI  =$254e
sstore_c_BASE_NUM  =$5e
powarc_s_select_best_power_step  =$645c; ?
rand_s_reset  =$8100; unused
INTERRUPTS_HI  =$40
MULTIPLIER  =$2
partsys_l_POWER_STEPS  =$5401
winslp_c_LINE_CENTER_Y  =$91
players_l_MATCH_PLAY_ORDER  =$564c
XCOS_HI  =$13; unused
ball_c_SIZE  =$133b; unused
target_determine_depth  =$7de1; ?
trees_c_MAX_TILES  =$10
winslp_v_rot_vz_lo  =$ba39; ?
winslp_c_LINE_CENTER_X  =$a
quads_l_TEXTURES  =$660c
SCR_CODE_POUND  =$1c; unused
spr_c_OFFSCREEN_R  =$58; unused
spr_s_clear_msb_all  =$ee2; unused
ball_c_SHADOW_SW_SPR_NUM  =$6
trees_v_collision_matrix_lo  =$aa59; ?
GOLFER_POS_MARKER_TRIG_INDICES  =$3b57; unused
playmsg_c_BEGIN  =$5782
wind_s_draw_speed  =$b95a; ?
trees_v_current_mask  =$af19
wind_v_quadrant  =$b89b; unused
waypts_rotate_to_pos_z_axis  =$b84b; ?
ingm_s_draw_tile_pattern  =$4886; ?
ball_vz_hi  =$25f2
ball_distance_z_lo  =$2640; unused
SP6COL  =$d02d; unused
trees_c_COLLISION_MATRIX_TOP_ROW  =$4; ?
hole_c_OVERHEAD_BALL_HW_SPR_NUM  =$0
powarc_c_PRECISION_END  =$1c; ?
quads_c_MAX_N  =$19
partsys_l_ALIVE_LOOKUP  =$53ee
POWARC_POWERING_UP_NUM_STEPS  =$24
sfx_l_MAX_POWER_INIT  =$89ad
COLORS_HI  =$28
snd_v_channel_active  =$1cd0
play_c_END_OF_SPRITES  =$d780; unused
maths_div16s  =$5254; ?
fmag_calc_force  =$4d9b; unused
bdrop_v_spr_color  =$221b
target_c_NUM_DEPTH_LEVELS  =$9
round_s_set_ball_position  =$857b; ?
VICIRQ  =$d019
trees_v_collision_matrix_hi  =$acb1; ?
tweeter_v_channel  =$bd25
trees_s_fix_color_clash  =$b4e7; ?
ZP_LOADER_10  =$69; unused
ball_s_check_collision  =$29fc
hole_s_draw_for_real  =$484c
round_l_FIRST_HOLE_TO_PLAY  =$816b
trees_v_trunk_col0  =$af13
golfer_s_restore_shadow  =$4464; ?
ZP_LOADER_11  =$6a; unused
dp_s_draw_string  =$15c7; unused
bdrop_s_draw_bg  =$227f
slope_l_RANDOM_MASKS  =$2480
powarc_s_update_max_animation  =$63a5; ?
ball_vz_lo  =$25f1
ball_distance_z_hi  =$2646; unused
GOLFER_PRECISION_ZONE_END  =$22; unused
playmsg_c_TYPE_BOGEY  =$1; unused
ZP_LOADER_12  =$6b; unused
spr_c_OFFSCREEN_T  =$1d; unused
golfer_c_RESPONSE_YES  =$1
sprd_c_LOADABLE_BASE  =$5e
trees_v_depth_in_feet  =$a787; ?
quads_c_VERTEX_STATE_OOB_LEFT  =$1
D6510  =$0; unused
COLORS_LO  =$27
SCR_CODE_AMPERSAND  =$26; unused
golfer_c_BEGIN  =$3b57
ball_c_PUTT_SUCCESSFUL  =$1
ball_s_check_target  =$2b6b; ?
golfer_c_MARKER_MOVE_DELAY_NORMAL  =$2
bdrop_l_POSITIONS_X  =$1e7c
sc_v_round_scores  =$86d2; ?
interrupts_v_state_change_request  =$4983
quads_s_reset_shimmers  =$7ad4
powarc_s_advance_precision  =$62ae; ?
PWHI1  =$d403; unused
PWLO3  =$d410; unused
SFX_DATA_ADDRS_ZP_HI  =$5b
ball_s_set_at_origin  =$266c
powarc_c_PRECISION_CENTER  =$14; ?
golfer_s_init_animate_hold  =$4280; ?
round_v_current_hole  =$8189; ?
sstore_c_SWING_LOWER_FEMALE  =$3
partsys_l_BYTE_PATTERNS  =$53e6
PWLO2  =$d409; unused
golfer_reset_crosshair  =$3f88; ?
sc_v_team_scores  =$86ae
wash_s_stop  =$bd0f; ?
i  =$10
PWLO1  =$d402; unused
POWARC_LO  =$39
msg_c_WAIT_STR  =$1c4c; unused
GOLFER_POS_MARKER_SPR_PTR  =$a2; unused
GOLFER_PUTTING_FRAME_RATE  =$8
quads_buffer_iter  =$6b11
PWHI3  =$d411; unused
bdrop_s_draw_distant_objects  =$22e4
PWHI2  =$d40a; unused
_DEBUG_APEX_  =$0
bmap_tiles_c_BEGIN  =$3862
GOLFER_SHADOW_POS_X_LO  =$86; unused
golfer_s_repair_msg_area  =$456b; ?
maths_l_TAN_LO  =$4e9c
transtn_s_update  =$bcac; ?
quads_project  =$7354
SFX_DATA_ADDRS_ZP_LO  =$5a
golfer_c_STATE_LOOKING_UP  =$1
ball_s_write_spr_data  =$34c2; ?
playmsg_s_praise_shot  =$5805; ?
waypts_c_SIZE  =$154; unused
gfxs_c_DISPLAY_OFFSET  =$20; unused
bdrop_v_spr_anim_type  =$2220
pythag_c_SIZE  =$140; unused
target_l_COLUMN_MASKS  =$7c15
trees_v_modulation_threshold  =$a505
trees_s_draw_trunk  =$b2f6; ?
POWARC_HI  =$3a
trees_v_collision_cut_off  =$a506
trees_s_write_foliage_masks  =$b25f; ?
ball_c_MIN_VY_ON_BOUNCE  =$2527
hole_s_init  =$4741
powarc_v_min_delay_reached  =$61ba
dp_l_BITMAP_PATTERNS  =$1274; unused
sc_s_write  =$86ef; ?
maths_l_TAN_HI  =$4edc
terrain_c_BEGIN  =$a3eb
transtn_c_BEGIN  =$bc25
golfer_v_kb_locked  =$3c90
golfer_s_update1_precision  =$423f; ?
winslp_l_BOX_ICON  =$b97e
SCR_CODE_PERIOD  =$2e; unused
spr_c_OFFSCREEN_B  =$fa
tweeter_s_spawn  =$bd4f; ?
sprd_c_GOLFER_PUTT_CONTACT_OFFSET  =$7
clubs_v_current_selection  =$3a87; ?
GOLFER_SETTING_SPIN  =$15; unused
partsys_l_VY_HI  =$53fc
target_s_build_sprite  =$7ead; ?
powarc_s_reset_putt_assist  =$63dc; ?
stats_l_BALLS_HOLED_MARKERS_ADDR_LO  =$a03b
tmarkers_c_BEGIN  =$a387
slope_l_INDICATOR_BYTE_END_OFFSETS  =$24ab
quads_x_lo  =$663a
RED  =$2
VM_LO  =$25
dp_l_COLOR_RAM_ROWS_HI  =$12a1
partsys_v_alive  =$5469
QUADS_NUM_BYTES_PER_QUAD  =$12
sfx_l_BALL_TREE_INIT  =$899c
dp_s_draw_line  =$13d8
GOLFER_POS_MARKER_SPR_NUM  =$6; ?
wash_c_SEQUENCE_LEN  =$6
target_v_current_depth  =$7c55; ?
hole_v_boundary_right_lo  =$4634; unused
round_c_MAX_PUTT_DISTANCE_LO  =$a4; ?
utils_l_BIT_LOOKUP  =$a66
spr_animate_loop  =$ea8
ball_s_init_water_splash_animation  =$3743; ?
quads_buf2_x_lo  =$6e92
trees_s_project  =$b0aa; ?
ball_v_drag_x_hi  =$2607
golfer_s_update1_concede_query  =$4509; ?
playmsg_l_ALERT_ADDR_LO  =$57e4
powarc_v_putt_assist_frame_count  =$61be
sprd_c_GOLFER_SWING_CLUB  =$35
sprd_c_GOLFER_PUTT_BACKSWING_FRAMES  =$4
bdrop_c_ANIM_PINGPONG  =$1; unused
maths_s_install_fine_trig  =$52b8; ?
trees_v_patterns  =$a507; unused
ball_l_BUNKER_POWER_REDUCTION  =$2528
round_l_LAST_HOLE_TO_PLAY_PLUS_ONE  =$816e
spr_v_edge  =$dcf; unused
round_v_msg_received  =$81a2
maths_s_check_operand_signs  =$527d; ?
stats_l_BALLS_HOLED_MARKERS_ADDR_HI  =$a03d
quads_x_hi  =$669e
YXPAND  =$d017; unused
dp_l_COLOR_RAM_ROWS_LO  =$1288
ball_c_DRAG_COEFFICIENT  =$c
ball_v_out_of_bounds  =$263b
target_c_POLE_COLLISION_MAX_DEPTH  =$7; ?
VM_HI  =$26
sc_c_SIZE  =$2b5; unused
spr_s_calc_dx  =$e25; unused
hole_v_boundary_right_hi  =$4635; unused
round_c_MAX_PUTT_DISTANCE_HI  =$1; ?
spr_s_calc_dy  =$e3b; unused
ball_v_drag_x_lo  =$2606
quads_buf2_x_hi  =$6e96
GOLFER_CLUB_SHAFT_SPR_NUM  =$1
playmsg_l_ALERT_ADDR_HI  =$57e7
w  =$7aa3; unused
MATHS7  =$11
bdrop_v_patterns  =$20ce; unused
clubs_l_PUNCH_VZ_LO  =$39d2; unused
sfx_c_MAX_POWER  =$7; ?
quads_l_FILL_BYTES  =$661b
trees_c_TRUNK_COLOR  =$2
bdrop_v_spr_sw_num  =$222a
maths_s_rotate  =$4ffc; ?
target_hw_spr_num  =$7c5a; ?
BALL_TREE_COLLISION_STATE_HANDLED  =$2
trees_v_temp_z_hi  =$af0b
ball_v_mutex_spr_y  =$25f9
ball_s_check_trunk_collision  =$3026; ?
MATHS6  =$10
MATHS5  =$f
play_c_SIZE  =$10; unused
golfer_v_p_key_locked  =$3c8e
powarc_v_putt_assist_suggested_step  =$61c1
ball_s_launch  =$2907
maths_mod08  =$5342; ?
sfx_c_BALL_TREE  =$6; ?
MATHS4  =$e
ball_s_swap_hw_spr_num  =$2e6b; ?
ball_s_reduce_velocity_xz  =$2e7d; ?
golfer_v_shot_spin_set  =$3c7c; ?
maths_mod09  =$5346; ?
trees_v_foliage_modulation_colors  =$a501
SPBGPR  =$d01b; unused
MATHS3  =$d
CAMERA3  =$20
utils_v_dec_digits  =$a76
ball_c_DISTANT_Z  =$834; ?
target_v_top_of_pole  =$7ca2; ?
clubs_l_PUNCH_VZ_HI  =$39df; unused
pythag_v_speed  =$6543; unused
trees_v_temp_z_lo  =$af0a
rand_v_seq  =$7fff
MATHS2  =$c
CAMERA2  =$1f
players_s_refresh_order_match_play  =$572f; ?
playmsg_c_TYPE_BIRDIE  =$3; unused
target_v_foliage_masks  =$7c62
quads_type  =$6621; ?
XXPAND  =$d01d
CAMERA1  =$1e
spr_c_OFFSCREEN_L  =$0; unused
BMAP_TILES_BG_TREES  =$3862; unused
MATHS1  =$b
font_s_prepare_colors  =$1aaf
sstore_c_SHOT_TYPE_PUTT_MALE  =$1
stats_l_PAR_STR  =$a00f
sstore_s_load_sequence  =$9fbf; ?
MATHS0  =$a
CAMERA0  =$1d
ball_v_splash_anim_count  =$2667
ball_c_TERRAIN_WATER  =$3
target_reset_base_position  =$7cc3; unused
sstore_c_DATA_PUTT_UPPER_FEMALE  =$9c46
kbmat_c_J  =$22; unused
shared_c_MATCH_PLAY  =$1
ball_c_SPIN_COEFFICIENT  =$96
hole_v_overhead_origin_x_hi  =$4638; ?
trees_s_setup_draw  =$b12c; ?
players_v_distance_lo  =$565c; ?
powarc_s_init_max_animation  =$636e; ?
powarc_c_PRECISION_DELTA  =$28
pythag_v_drag_force_lo  =$6544; unused
camera_c_SIZE  =$13c; unused
maths_mod4  =$5084
SFDX  =$cb; unused
kbmat_c_K  =$25; unused
joy_v_up_locked  =$9dd
spr_s_clamp_right  =$e65; unused
golfer_l_TRIG_INDICES  =$3be6; unused
powarc_s_reset  =$6210
ball_v_mutex_spin_x_lo  =$2618
quads_rot_x_lo  =$695a
ball_s_reduce_power  =$2ef6; ?
trees_v_trunk_adjusts  =$a4d9
maths_mod5  =$5089
SP1COL  =$d028; unused
sprd_c_GOLFER_MIDSWING_OFFSET  =$5
bdrop_l_AVAILABLE_HW_SPRITES  =$1f27
ball_l_PUTTING_FRICTION_COEFFICIENTS  =$2582
golfer_s_update0_hold_putt  =$430a; ?
maths_c_SIZE  =$5e0; unused
kbmat_c_H  =$1d; unused
maths_mod6  =$50bd
quads_c_SIZE  =$15e0; unused
GREEN  =$5
WS_X_HI  =$30
quads_l_TEXTURE_COLORS  =$65fd
kbmat_c_I  =$21; unused
ball_l_ELASTICITY  =$252b
quads_buf2_max_z_hi  =$6ea3
maths_mod7  =$50c2
kbmat_c_N  =$27; unused
bdrop_v_spr_active  =$2225
hole_v_overhead_origin_x_lo  =$4637; ?
powarc_v_max_animation_active  =$61bb
players_v_distance_hi  =$5660; ?
golfer_pos_marker_direction  =$3c79
pythag_v_drag_force_hi  =$6545; unused
maths_mod0  =$5012
kbmat_c_O  =$26; unused
joy_c_DOWN  =$2
quads_rot_x_hi  =$69be
ball_v_mutex_spin_x_hi  =$2619
partsys_s_init  =$546b; ?
players_c_JOY1  =$1; unused
GOLFER_POS_MARKER_MIN_X  =$84; unused
target_v_fabric_color  =$7ca3; ?
ball_v_splash_anim_iter  =$2666
maths_mod1  =$5017
kbmat_c_L  =$2a; unused
bdrop_s_init  =$2237
GOLFER_POS_PUTTING_X_OFFSET  =$18
golfer_s_update1  =$3dbf
ingm_s_default_draw_tile  =$4959; ?
players_c_JOY2  =$0; unused
clubs_s_next  =$3a8f
maths_mod2  =$504b
WS_X_LO  =$2f
kbmat_c_M  =$24; unused
quads_buf2_max_z_lo  =$6ea2
round_s_rotate_world  =$835e
maths_mod3  =$5050
ATDCY3  =$d413; unused
joy_v_left_locked  =$9e1
shared_c_MAX_TEAM_NAME_LEN  =$15
sfx_c_SPLASH  =$5; ?
kbmat_c_B  =$1c; unused
ball_s_calc_distance_of_shot  =$33c7
tweeter_v_current_wait  =$bd26
dp_s_build_mask  =$159a
ball_world_z_lo  =$262a
sstore_c_SIZE  =$15c0; unused
DS0  =$14b; unused
ATDCY2  =$d40c; unused
BALL_TRI_X_HI  =$36
kbmat_c_C  =$14; unused
utils_s_ror_two_bits  =$b15; unused
shared_v_greens_difficulty  =$16c5
DS1  =$296; unused
ATDCY1  =$d405; unused
target_l_FABRIC_PATTERN_DEST_OFFSETS  =$7c3c
clubs_c_SIZE  =$1b9; unused
waypts_z_lo  =$b72d
DS2  =$52c; unused
kbmat_c_A  =$a; unused
shared_l_CHARS_FOR_SCORE_ZERO  =$164a
snd_v_data_address_lo  =$1cdf; unused
snd_s_clear_all  =$1e46
ball_s_precalculate_bounce  =$37dd; ?
ball_l_LIE_OFFSETS  =$25d9
hole_c_PULSE_COLORS  =$462a
sfx_l_BALL_TREE_DATA  =$89aa
RESULT  =$2
snd_s_set_max_volume  =$1ce7
playmsg_l_ALERT_LENS  =$57ea
hole_v_overhead_ball_x_lo  =$473b; ?
DS3  =$a58; unused
kbmat_c_F  =$15; unused
winslp_c_ARROW_LEN  =$60; ?
ball_c_SPR_ADDRESS  =$ccc0
round_v_current_player  =$818b; ?
ball_world_z_hi  =$262b
DS4  =$14b2; unused
BALL_TRI_X_LO  =$35
shared_v_player_name_indices  =$1679
kbmat_c_G  =$1a; unused
gfxs_c_SPR_PTR_BASE  =$cbf8; unused
hole_current_rotation_angle  =$4645; ?
transtn_v_is_active  =$bc26; ?
GOLFER_LOWER_BODY_SPR_NUM  =$3
DS5  =$2963; unused
kbmat_c_D  =$12; unused
camera_project_onto_plate_y  =$3863; ?
GOLFER_WATCHING_CLUB_OFFSET_Y  =$aa
powarc_v_power_maxed_out  =$6096; ?
trees_v_trunk_widths  =$a4cf
ttrunks_c_SIZE  =$1eb; unused
waypts_z_hi  =$b730
DS6  =$52c7; unused
kbmat_c_E  =$e; unused
snd_v_data_address_hi  =$1ce2; unused
bdrop_c_BEGIN  =$1e7c
GOLFER_WATCHING_CLUB_OFFSET_X  =$96
ball_v_is_drag_invalid_for_roll  =$2669
camera_project_onto_plate_x  =$3915; ?
powarc_c_SLOW_MARKER_DATA  =$607f
target_s_draw_shadow  =$7fbd
snd_v_SIGVOL_buffer  =$1ce6; unused
hole_v_overhead_ball_x_hi  =$473c; ?
players_s_compare_score  =$56d6
play_l_OVERHEAD_BALL_SPRITE  =$d700
partsys_c_G_DELAY  =$1; unused
DS7  =$a58f
kbmat_c_Z  =$c; unused
golfer_c_MARKER_INITIAL_INDEX  =$10; ?
golfer_look_up_count  =$3c76
CAMERA_Y_HI  =$0
maths_l_COS_LO  =$4e1c
partsys_l_SPR_ROWS_HI  =$53d1
quads_clear_everything  =$7643; unused
players_s_reset  =$567c
bdrop_v_spr_hires  =$2216
A0  =$1d4; unused
C1  =$22c; unused
E2  =$57b; unused
G3  =$d09; unused
ball_c_GRAVITY  =$a
GOLFER_SPIN_THRESHOLD  =$6
golfer_c_STATE_ANIMATE_HOLD  =$7
C0  =$116; unused
G2  =$684; unused
E3  =$af6; unused
A1  =$3a8; unused
SCR_CODE_9  =$39; unused
gfxs_c_DISPLAY_BASE  =$c800
ball_c_SPIN_TYPE_SLICE  =$2
ball_temp_aa_z_lo  =$25f5
golfer_s_animate_swing  =$416f; ?
sc_v_pars  =$8654; ?
terrain_l_SAND_COLORS  =$a3ef
kbmat_c_X  =$17; unused
stats_c_SIZE  =$381; unused
E0  =$15e; unused
G1  =$342; unused
A2  =$751; unused
C3  =$8b3; unused
CURSOR_POS_HI  =$4b
SCR_CODE_8  =$38; unused
clubs_l_MIN_CLUBS  =$3a83
players_s_refresh_order  =$56ed
quads_solve_linear_x  =$7764; ?
round_s_draw_direction  =$83de
waypts_aa_x_lo  =$b733
kbmat_c_Y  =$19; unused
end_of_loader  =$9c6; unused
spr_v_x_hi  =$c5e
partsys_c_ORIGIN_X  =$c
G0  =$1a1; unused
E1  =$2bd; unused
C2  =$459; unused
A3  =$ea2; unused
joy_c_LEFT  =$4
ball_s_handle_water_splash  =$2c05; ?
sstore_c_DATA_PUTT_UPPER_MALE  =$9946
interrupts_c_MIDDLE  =$1
snd_v_gates  =$1cdc; unused
bdrop_s_draw_pattern  =$2327; ?
round_v_must_putt  =$818f; ?
partsys_l_SPR_ROWS_LO  =$53bc
CAMERA_Y_LO  =$40
golfer_s_update0_hold2  =$4272; ?
maths_l_COS_HI  =$4e5c
A4  =$1d44; unused
C5  =$22ce; unused
E6  =$57b4; unused
G7  =$d098; unused
SCR_CODE_PLUS  =$2b; unused
sprd_c_GOLFER_PUTT_CLUB  =$43
app_s_run_nineteenth  =$c38; unused
quads_rot_max_z_points  =$6de2; unused
shared_c_NUM_SHIRT_COLORS  =$6; unused
ball_v_applying_spin  =$263a
clubs_c_SW  =$b
golfer_v_current_state  =$3c75
C4  =$1167; unused
G6  =$684c; unused
E7  =$af68
A5  =$3a88; unused
ball_temp_aa_z_hi  =$25f6
stats_l_UNITS_TEXT_OFFSETS  =$a00d; ?
interrupts_c_BEGIN  =$497d
E4  =$15ed; unused
G5  =$3426; unused
A6  =$7511; unused
C7  =$8b38
CURSOR_POS_LO  =$4a
golfer_init2  =$3eb4
powarc_s_advance_power  =$6259; ?
waypts_aa_x_hi  =$b734
spr_v_x_lo  =$c4e
powarc_v_bitmap_copy  =$6098; ?
G4  =$1a13; unused
E5  =$2bd9; unused
C6  =$459c; unused
A7  =$ea23
SIGVOL  =$d418; unused
golfer_l_SHADOW_POS_HI  =$3c4f
target_l_FABRIC_COLORS  =$7be1
SCR_CODE_3  =$33; unused
kbmat_c_R  =$11; unused
GOLFER_POS_MARKER_Y  =$c6
wind_v_vx_hi  =$b898
SCR_CODE_2  =$32; unused
ball_c_BUMP_VY_LO  =$50
ball_s_check_pole_collision  =$367b; ?
CAMERA_PLATE_Z_LO  =$ea
wind_c_BEGIN  =$b86b
kbmat_c_S  =$d; unused
GOLFER_POS_MARKER_X  =$b6
trees_v_x_lo  =$a789
SCR_CODE_1  =$31
spr_v_fg_priority  =$dce; unused
ball_c_SPR_PATTERN_FULL_SIZE  =$0
ball_v_mutex_lock  =$262f
target_c_BEGIN  =$7be1
hole_v_boundary_aa_right_lo  =$4640; ?
round_s_prepare_hole  =$85ef; ?
kbmat_c_P  =$29
bdrop_v_columns  =$1f36
round_v_teeing_off  =$818d; ?
SPMC  =$d01c; unused
SND_REGS_BASE_ZP_LO  =$56; unused
SCR_CODE_0  =$30
spr_v_bg_priority  =$dae
players_v_ball_pos_z_hi  =$5674; ?
round_c_MSG_CONCEDE_HOLE  =$3; ?
powarc_s_update_putt_assist  =$63f8; ?
sfx_l_MAX_POWER_DATA  =$89bb
bdrop_s_draw_all  =$2476
kbmat_c_Q  =$3e; unused
hole_v_overhead_scale_hi  =$463b; ?
SCR_CODE_7  =$37; unused
ball_l_SPR_DATA_SMALL_ROW1  =$25a6; unused
golfer_l_SHADOW_POS_LO  =$3c4d
partsys_c_SPR_DATA_ADDR  =$cc40
quads_rot_min_z_points  =$6dc9; unused
kbmat_c_V  =$1f; unused
icon_s_draw  =$1af6
wind_v_vx_lo  =$b897
SCR_CODE_6  =$36; unused
SCR_CODE_COLON  =$3a
ball_l_COLLISION_SMALL  =$25aa; unused
CAMERA_PLATE_Z_HI  =$fe
ball_c_BUMP_VY_HI  =$0
ball_l_SPR_DATA_SMALL_ROW0  =$25a2; unused
kbmat_c_W  =$9; unused
trees_v_x_hi  =$a7d9
SCR_CODE_5  =$35; unused
quads_buf2_size  =$6e91
hole_v_boundary_aa_right_hi  =$4641; ?
kbmat_c_T  =$16; unused
SND_REGS_BASE_ZP_HI  =$57; unused
SCR_CODE_4  =$34; unused
dp_s_set_video_ram_cell  =$1582; unused
font_s_shift_text_right  =$1adf
ball_v_is_distant  =$2665
ball_s_display_distance_of_shot  =$342c
players_v_ball_pos_z_lo  =$5670; ?
target_l_FABRIC_PATTERNS  =$7c19
kbmat_c_U  =$1e; unused
hole_v_overhead_scale_lo  =$463a; ?
sprd_c_GOLFER_WATCHING_SWING_CLUB  =$4d
bdrop_v_spr_hw_num  =$222f
quads_aa_z_hi  =$68f6; ?
golfer_v_spr_pointer_buffer  =$3c87
maths_l_FINE_SIN_LO  =$4f5e
trees_v_heights  =$a4bb
target_base_x_hi  =$7c4e
tmarkers_c_SHADOW_OFFSETS1  =$a392
clubs_l_DISTANCE_STR_OFFSETS  =$3a56
GOLFER_WATCHING_UPPER_OFFSET_Y  =$bf
ball_c_BEHIND_HOLE  =$1
ball_v_mutex_spr_x_lo  =$25f7
ball_v_mutex_spin_y_lo  =$261a
stats_l_BALLS_HOLED_TEAM_OFFSETS  =$a036
clubs_l_VY_LO  =$39b8; ?
clubs_s_select_best_club  =$3b1a
terrain_c_VIDEO_RAM_BASE  =$cb71
powarc_v_frame_count  =$6091
GOLFER_WATCHING_UPPER_OFFSET_X  =$94
SP0COL  =$d027
play_c_BEGIN  =$1e6c
golfer_c_STATE_POWERING_UP  =$2
golfer_s_store_new_ball_position  =$4153
bdrop_s_prepare_draw  =$233c
GOLFER_PUTT_POS_X  =$a4
FADE_CR_SRC_LO  =$46
ball_s_check_depth  =$2758
msg_c_FISHING_STR  =$1c2b; unused
bdrop_l_TILES_ADDR_LO  =$1ec7
GOLFER_PUTT_POS_Y  =$be
golfer_keyboard_locked  =$3c7f
zsin_hi  =$4ffb
quads_max_z_hi  =$6aed
powarc_c_PRECISION_BEGIN  =$c; ?
ball_s_update_full_tilt  =$2d06
golfer_v_frame_count  =$3c77
kbmat_c_RUNSTOP  =$3f
quads_aa_z_lo  =$6892; ?
round_c_SCORE_TABLE_CODE_MATCH_PLAY_FILENAME  =$817d
maths_l_FINE_SIN_HI  =$4f7f
sc_c_BEGIN  =$8654
powarc_v_putt_assist_color_index  =$61bf
target_base_x_lo  =$7c4d
target_init  =$7ca4
RANDOM_X_TMP  =$41
ball_v_mutex_spr_x_hi  =$25f8
shared_c_FEMALE  =$1; unused
ball_v_mutex_spin_y_hi  =$261b
ball_s_calc_current_row_and_column  =$3519; ?
golfer_s_push_off_screen  =$457b
clubs_l_VY_HI  =$39c5; ?
ball_s_check_for_scuffed_shot  =$2f2b; ?
clubs_c_3W  =$1
bdrop_s_find_active_hw_sprites  =$2412
transtn_s_blank_one_row  =$bc52
golfer_c_STATE_FINISHED  =$a
FADE_CR_SRC_HI  =$47
SCR_CODE_LT  =$3c
utils_c_HEX2DEC_RESULT_SIZE_BYTES  =$5; unused
bdrop_l_TILES_ADDR_HI  =$1ef7
quads_max_z_lo  =$6aec
zsin_lo  =$4ffa
bdrop_s_init_sprite  =$2355; ?
ball_l_COLLISION_EVEN  =$2592; unused
ball_c_STATE_SPLASHING  =$ffffffff
quads_rot_max_z_lo  =$6d97
sprd_c_GOLFER_PUTT_LOOKING_UP  =$5e
waypts_c_BEGIN  =$b717
sprd_c_GOLFER_PUTT_MIDSWING_OFFSET  =$4
ball_v_putting_vx_hi_before  =$2663
stats_s_draw_current_shots_no_check  =$a23f
dp_l_BITMAP_COLS_HI  =$11d0
ball_v_mutex_vz_hi  =$2605
maths_mul16s  =$522b; ?
trees_v_col0  =$af11
SCR_CODE_PERCENT  =$25; unused
joy_v_down_locked  =$9df
dp_l_CHARS_LO  =$12ec; unused
ball_v_last_mc_x  =$2636
players_s_prepare_next_hole  =$5755
round_windslope_rotate  =$83d1; ?
tmarkers_c_CRAM_DEST0  =$db7d
msg_c_CONCEDE_STR  =$1c38; unused
slope_l_INDICATOR_BYTES  =$248b
target_v_overlap_char_r  =$7c5c
quads_edges_from  =$6b2e
wind_s_init  =$b89d; ?
app_v_filename  =$bc8; unused
xsin_hi  =$4ff7
sc_s_prepare_score_str  =$872e
partsys_l_LAND_DELTA_MASK  =$5414
waypts_calc_rotation  =$b805; ?
stats_s_draw_current_shots  =$a239; ?
sstore_c_PUTT_LOWER_FEMALE  =$7
tmarkers_c_CRAM_DEST1  =$db8a
sc_s_draw_name_and_score  =$879f; ?
wash_s_init  =$bccb; ?
snd_v_must_loop  =$1cd9; unused
sstore_l_NUM_SPRITES  =$9f66
trees_v_foliage_offsets  =$a4e3
ball_c_SLOW_DOWN_ON_BUMP_LO  =$96
target_v_overlap_char_t  =$7c5d
quads_rot_max_z_hi  =$6db0
dp_l_BITMAP_COLS_LO  =$1130
golfer_l_SHADOW_PATTERN  =$3c3d
ball_v_mutex_vz_lo  =$2604
ball_v_hw_spr_num  =$2630
gfxs_s_init_colors  =$b6d
dp_l_CHARS_HI  =$132c; unused
msg_v_last_len  =$1c69; unused
fmag_s_cross_product  =$4b52; ?
sstore_init  =$a000; ?
trees_v_n  =$a788
sstore_s_copy  =$9f6f
GOLFER_SHADOW_POS_Y  =$e8; unused
tweeter_s_turn_on  =$bd7f; ?
sstore_c_DATA_SWING_LOWER_MALE  =$8e46
xsin_lo  =$4ff6
RESON  =$d417; unused
bdrop_v_num_distant_objects  =$1f35; unused
golfer_c_MIN_PRAISEWORTHY_PUTT_FT  =$69; ?
partsys_l_BASE_LAND  =$540a
partsys_v_n  =$541d
quads_c_MIN_DRAWABLE_DEPTH  =$2
stats_s_draw_all  =$a374; ?
round_s_load_hole  =$81d1
golfer_s_check_hidden  =$43c1; ?
sstore_c_DATA_SWING_LOWER_FEMALE  =$95c6
powarc_l_BASE_BITMAP_ICON  =$5e94
target_coll_lower_z_hi  =$7c57
trees_c_DEPTH_IN_FEET  =$23; ?; unused
SND_INIT_DATA_ZP_LO  =$54; unused
target_v_overlap_offset_y  =$7c60
SCR_CODE_DOUBLE_QUOTE  =$22; unused
quads_v_states  =$6ea8
trees_s_load  =$af21; ?
FADE_SR_SRC_LO  =$48; unused
gfxs_c_BITMAP_BASE  =$e000
round_v_must_render  =$8190
trees_l_CMLO_ADDR_LO  =$a437; ?
trees_l_CMHI_ADDR_HI  =$a464; ?
tmarkers_c_VRAM_VALUE  =$35
shared_v_course_index  =$16c1
ball_v_spin_axis_x_hi  =$2654
trees_l_SHADOW_MASKS  =$a493
powarc_c_PRECISION_BUNKER_END  =$18; ?
interrupts_l_SPLITS  =$497d
target_v_overlap_offset_x  =$7c5f
round_s_clear_non_scenery_sprites  =$844d
winslp_v_final_vx_lo  =$ba3b; ?
CI2PRA  =$dd00; unused
trees_s_prepare_for_trunk_above_horizon  =$b4a5; ?
round_c_MSG_NEXT_SHOT  =$2; ?
BLUE  =$6
sprd_c_CROSSHAIR  =$4e
target_v_overlap_char_l  =$7c5b
gfxs_c_COLOR_RAM_OFFSET  =$1000; unused
shared_v_team_names  =$168d; unused
ball_c_TERRAIN_ROUGH  =$0
tweeter_s_turn_off  =$bd86; ?
maths_mul16  =$4fce; ?
clubs_l_DISTANCE_BUFF  =$3a80
powarc_c_TOP_ROW  =$11
trees_s_clear_collision_matrix  =$b090; ?
target_coll_lower_z_lo  =$7c56
GOLFER_FORESWING_FRAME_RATE  =$7
SND_INIT_DATA_ZP_HI  =$55; unused
hole_v_pulse_iter  =$473f
tmarkers_c_SHADOW_PATTERNS1  =$a38f
joy_s_release_all_locks  =$a04; unused
interrupts_s_clean_up  =$49a1
FADE_SR_SRC_HI  =$49; unused
msg_l_MSG_LENGTHS  =$1c64; unused
ball_c_ROLLING_MIN_VZ  =$2581
trees_l_CMLO_ADDR_HI  =$a446; ?
trees_l_CMHI_ADDR_LO  =$a455; ?
SCR_CODE_SLASH  =$2f
spr_s_clamp_left  =$e51; unused
ball_v_spin_axis_x_lo  =$2653
winslp_v_final_vx_hi  =$ba3c; ?
sprd_c_GOLFER_PUTT_UPPER  =$5f
shared_v_player_names  =$164c; unused
players_s_compare_distance  =$56b1
msg_c_OUT_OF_BOUNDS  =$0
winslp_s_apply  =$ba41; ?
quads_init_drawing_order  =$78a9; ?
ball_c_STATE_IN_FLIGHT  =$2
spin_here  =$31ca; unused
clubs_c_5I  =$5
sprd_c_GOLFER_FORESWING_FRAMES  =$9
app_s_run_splash  =$c15; unused
spr_c_CURRENT_CHAR_ZP_LO  =$3b; unused
BALL_SCUFFED_SHOT_VZ_HI  =$0
golfer_init_poised  =$411b; unused
font_l_CHAR_DATA_HI  =$19db; unused
golfer_c_HOLD_DURATION  =$14
dp_s_draw_byte  =$13b4
msg_c_CONCEDE_HOLE  =$3
ball_v_mutex_drag_z_lo  =$2610
quads_s_project_and_draw  =$7600
round_c_BEGIN  =$815c
ball_v_apparent_vz_hi  =$2627
target_v_overlap_char_b  =$7c5e
slope_c_SIZE  =$a7; unused
golfer_c_HOLD_TIME_SWING_COMPLETE  =$28
round_c_STATE_SCORE_CARDS  =$2; ?
trees_s_init_drawing_order  =$af6b; ?
interrupts_s_do_shot_complete  =$4aa5; ?
trees_s_write_collision_matrix  =$b2a1; ?
SP5X  =$d00a; unused
SP7Y  =$d00f; unused
CB_LOADFILE  =$59c; unused
snd_c_FILTER_BANDPASS  =$20; unused
trees_v_tiles  =$a707; ?
tweeter_v_is_last_wait  =$bd27
terrain_l_COLORS  =$a3eb
slope_s_draw  =$250d
SP5Y  =$d00b; unused
SP7X  =$d00e; unused
MEMSIZ  =$37; unused
spr_c_CURRENT_CHAR_ZP_HI  =$3c; unused
snd_s_real_init  =$1d1a; unused
BALL_SCUFFED_SHOT_VZ_LO  =$5a
font_l_CHAR_DATA_LO  =$1980; unused
SP1X  =$d002; unused
SP3Y  =$d007; unused
ball_v_mutex_drag_z_hi  =$2611
sc_v_scores  =$8666
ball_v_apparent_vz_lo  =$2626
ttrunks_s_reset  =$b70c; ?
LOAD  =$ffd5; unused
hole_v_par  =$4636; ?
SP1Y  =$d003; unused
SP3X  =$d006; unused
sprd_c_BALL  =$33
powarc_c_MAX_SW_SPR_NUM  =$f
round_v_current_player_is_on_green  =$818c; ?
winslp_s_draw_box  =$ba73; ?
SUREL2  =$d40d; unused
FADE_SR_HI  =$45; unused
dp_s_record_edge  =$155f; unused
quads_c_VERTEX_STATE_IN_BOUNDS  =$0
golfer_l_MARKER_Y_POS2  =$3bc5
interrupts_s_do_score_cards  =$4afc; ?
SUREL3  =$d414; unused
FADE_CR_HI  =$43
joy_s_is_horizontal  =$9e8; unused
ball_v_mutex_spin_z_lo  =$261c
powarc_v_power_up_speed  =$61c3
quads_rot_z_lo  =$6a22
round_c_MSG_NONE  =$0; unused
dp_c_BITMAP_START  =$e000; unused
clubs_l_VZ_LO  =$399e; ?
SP3COL  =$d02a; unused
ingm_mod0  =$490d; ?
ball_v_current_state  =$262c
quads_c_SHIMMER_FRAME_RATE  =$a
golfer_l_ANTI_SHADOW_BUFFER  =$3c51
rand_c_MIX_LIMIT  =$40
stats_l_BALLS_HOLED_TOTAL_OFFSETS  =$a038
SUREL1  =$d406; unused
WS_Z_HI  =$32; unused
utils_l_HEX2DEC_LOOKUP  =$a16; unused
golfer_shot_power_finalized  =$3c7b
quads_c_MAX_SHIMMERS  =$40
spr_v_framerate  =$d3e
playmsg_s_clear_buffer  =$5859; ?
golfer_s_toggle_concede_response  =$44c4; ?
trees_l_TILES_ADDR_LO  =$a473
FADE_SR_LO  =$44
spr_v_anim_start_ptr  =$cfe
spr_v_xxpand  =$d9e
slope_c_INDICATOR_DEST_BASE  =$f7c8
ball_v_shadow_hw_spr_num  =$2631
golfer_s_setup_draw  =$3de7
round_c_STATE_WIPING_SCREEN  =$3
FADE_CR_LO  =$42
ball_v_mutex_spin_z_hi  =$261d
players_s_reset_distance  =$5688
playmsg_c_NUM_ADJECTIVES  =$4; unused
sstore_c_SHOT_TYPE_PUTT_FEMALE  =$3; unused
quads_rot_z_hi  =$6a86
clubs_l_VZ_HI  =$39ab; ?
GOLFER_POWERING_UP  =$14; unused
sc_s_reset_all  =$86e2; ?
spr_v_current_ptr  =$d4e
msg_s_display_stock_msg  =$1c7e
ball_l_SPR_DATA_EVEN_ROW1  =$258e; unused
WS_Z_LO  =$31; unused
spr_s_move_down  =$e13; unused
quads_max_y_lo  =$6af1
sstore_c_PUTT_LOWER_MALE  =$5
font_l_SHIFT_RIGHT_BYTES  =$1a56; unused
slope_l_RANDOM_ADDENDS  =$2483
ball_l_SPR_DATA_EVEN_ROW0  =$258a
trees_l_TILES_ADDR_HI  =$a483
BGCOL3  =$d024; unused
ball_y_fraction  =$25ec
maths_adjust_vec_signs  =$5111; ?
GOLFER_POS_MARKER_VX_HI  =$0
sstore_c_SWING_LOWER_MALE  =$1
C2DDRA  =$dd02; unused
sfx_c_BROWSE  =$0; ?
golfer_l_MARKER_X_POS2  =$3ba4
players_v_playing_order  =$5658
golfer_s_record_terrain  =$4608
msg_c_SIZE  =$bd; unused
ball_world_x_lo  =$2628
powarc_s_toggle_power_up_speed  =$6478; ?
partsys_s_copy_buffer_to_vram  =$5632; ?
hole_c_SIZE  =$22f; unused
trees_s_sort  =$b05a; ?
AS1  =$3e0; unused
BGCOL2  =$d023; unused
BALL_TRI_Z_HI  =$38
spr_v_y  =$c6e
snd_c_FILTER_LOWPASS  =$10; unused
ball_v_mutex_vy_hi  =$2603
waypts_current_i  =$b738
spr_v_vy_hi  =$cae; unused
powarc_iter  =$6092
waypts_load  =$b79b; ?
AS0  =$1f0; unused
BGCOL1  =$d022; unused
dp_l_VIDEO_RAM_ROWS_HI  =$12d3
ball_v_current_speed  =$261e
wash_c_DEST_BASE  =$cbc0
gfxs_s_clear_bitmap  =$b4b
ball_s_calc_initial_velocity  =$2841
wash_v_active  =$bcc9; ?
wash_v_duration  =$bcca
partsys_l_LAND_DELTA_MAX  =$540f
CAMERA_Z_MINUS_PLATE_Z_HI  =$0
waypts_x_lo  =$b727
AS3  =$f80; unused
BGCOL0  =$d021
POWARC_FILL_SRC_ITER_HI  =$3c
PUTT_ASSIST_SRC_ZP_HI  =$5d
pythag_s_calc_magnitude  =$6547; ?
AS2  =$7c0; unused
trees_v_trunk_row0  =$af12
sprd_c_GOLFER_LOOKING_UP  =$5e
spr_v_yxpand  =$d8e
sstore_c_PUTT_UPPER_FEMALE  =$6
msg_c_OUT_OF_BOUNDS_STR  =$1c0a; unused
GOLFER_POS_MARKER_VX_LO  =$c8
ball_world_x_hi  =$2629
winslp_s_draw_direction  =$baa7; ?
AS5  =$3e04; unused
BALL_TRI_Z_LO  =$37
SCR_CODE_HASH  =$23; unused
joy_c_FIRE  =$10
ball_v_mutex_vy_lo  =$2602
golfer_s_update1_preswing  =$3fb8; ?
spr_v_vy_lo  =$c9e; unused
rand_s_get_fast  =$814b; ?
AS4  =$1f01; unused
SIGN_CHANGED  =$1a
WAYPTS_MAX  =$3
spr_s_sync_msb  =$ec7; unused
dp_l_VIDEO_RAM_ROWS_LO  =$12ba
trees_c_COLLISION_MATRIX_BOTTOM_ROW  =$12; ?
CAMERA_Z_MINUS_PLATE_Z_LO  =$7d
AS7  =$f810; unused
waypts_x_hi  =$b72a
POWARC_FILL_SRC_ITER_LO  =$3b
PUTT_ASSIST_SRC_ZP_LO  =$5c
sfx_l_SWISH_INIT  =$8934
golfer_c_STATE_HOLD  =$3
target_l_TOP_OF_POLE_OFFSETS  =$7bfa
AS6  =$7c08; unused
CYAN  =$3
snd_l_REGS_BASE_ADDR_LO  =$1cc7; unused
golfer_l_SHADOW_BUFFER  =$3c61
target_get_distance  =$7d3e; unused
sfx_l_DATA_ADDRS  =$8a21
trees_v_depth_index  =$af0e
round_v_current_sky_color  =$8193; ?
powarc_c_INITIAL_DELAY_LO  =$32
transtn_v_current_row  =$bc25
quads_s_load  =$702b
quads_rotate  =$75a4
ball_v_must_launch  =$263c
ttrunks_v_depths_z_lo  =$b52c; ?
quads_v_frame_counts  =$6ee8
spr_v_anim_seq_inc  =$d1e
players_c_SIZE  =$136; unused
waypts_box_x1_lo  =$b71f
waypts_box_z0_lo  =$b71b
msg_c_WAIT  =$4
ball_c_LIE_STRINGS  =$25b0
ball_c_IN_FRONT_OF_HOLE  =$ffffffff
ball_temp_aa_x_lo  =$25f3
hole_c_BOUNDARY_BOTTOM_HI  =$fb; ?
quads_c_VERTEX_STATE_UNSET  =$ffffffff
interrupts_s_uninstall  =$49a7
quads_copy_current_to_buffer  =$79a4; ?
wind_l_RANDOM_MASKS  =$b86b
SCR_CODE_COMMA  =$2c; unused
shared_v_random_seed  =$16c7
ball_s_set_spin_type  =$334f; ?
partsys_y_hi  =$5436
quads_refresh_drawing_order  =$78d0; ?
maths_l_SIN_LO  =$4d9c
waypts_aa_z_lo  =$b735
snd_l_REGS_BASE_ADDR_HI  =$1cca; unused
ball_v_current_spr_pattern  =$2664; unused
powarc_c_INITIAL_DELAY_HI  =$5
sfx_c_BIRD1  =$8
quads_buf2_max_z_i  =$6ea6
sprd_c_BALL_SHADOW  =$34
ball_s_handle_tree_collision  =$2edf; ?
golfer_c_STATE_HOLD2  =$5
ttrunks_v_depths_z_hi  =$b5cc; ?
partsys_l_HOW_MANY  =$5405
quads_buffer_proj  =$6b12
quads_edges_to  =$6c2e
spr_s_move_left  =$dd1; unused
quads_draw_filled  =$73e1
waypts_box_x1_hi  =$b721
ball_temp_aa_x_hi  =$25f4
POWARC_STEP_THRESHOLD  =$3; unused
waypts_box_z0_hi  =$b71d
sstore_c_DATA_SWING_UPPER_FEMALE  =$91c6
stats_c_BEGIN  =$a006
hole_c_BOUNDARY_BOTTOM_LO  =$e6; ?
powarc_c_PRECISION_BUNKER_BEGIN  =$10; ?
quads_s_texture_fway_sand  =$7b96; ?
stats_s_inc_current_shots  =$a2b9; ?
golfer_s_hide_shadow  =$444c; ?
partsys_y_lo  =$542e
quads_wbuf_iter  =$6d4a
round_c_LOADING_MSG_LEN  =$f
maths_l_SIN_HI  =$4ddc
sfx_c_BIRD2  =$9; unused
waypts_aa_z_hi  =$b736
bdrop_v_pattern_start_rows  =$1f3c
golfer_v_marker_move_delay  =$3c8d
interrupts_s_cb  =$49fd; ?
sfx_l_BALL_CLUB_DATA  =$8968
ttrunks_c_BEGIN  =$b52c
wind_v_vz_hi  =$b89a
spr_v_anim_end_ptr  =$d0e
shared_v_player_name_lens  =$1675
ball_c_STATE_MUST_INIT  =$1
powarc_v_step_count  =$6093; ?
BALL_SCUFFED_SHOT_VY_HI  =$0
golfer_c_MARKER_MOVE_DELAY_SLOW  =$8
quads_v_shimmers_bitmap_addrs_hi  =$6fe8
stats_v_balls_holed  =$a053
clubs_c_MAX_ALLOWED  =$b
partsys_vx_hi  =$5446
quads_c_MAX_BUFFER_SIZE  =$1c
trees_v_z_lo  =$a829
CIAPRA  =$dc00
ball_v_mutex_drag_y_lo  =$260e; unused
SCR_CODE_LEFT  =$1f; unused
clubs_c_BEGIN  =$399e
CLUBS_PUTTER_I  =$c
golfer_s_init_swing_animation  =$3cbb
tmarkers_s_draw  =$a395; ?
ball_v_apparent_vy_hi  =$2625
snd_s_init_sfx  =$1cf0
bdrop_v_spr_x_offset_hi  =$2202
ball_s_check_triangle  =$2f82; ?
players_v_ball_pos_x_hi  =$566c; ?
powarc_l_BITMAP_COPY_ROWS_HI  =$5e8e
wind_s_rotate  =$b8d9; ?
sstore_c_BEGIN  =$8a46
trees_s_count_color_codes  =$b4c1; ?
partsys_s_update  =$5535; ?
partsys_c_MAX_PARTICLES  =$8
maths_l_MUST_NEGATE  =$4fa4
msg_c_SCORE_CARDS_STR  =$1c18; unused
snd_c_SIZE  =$1a5; unused
bdrop_v_tiles  =$1f42; ?
ball_s_update_splash_animation  =$3794; ?
wind_v_vz_lo  =$b899
CB_INITLOADER  =$3000; unused
utils_s_write_digits_to_buffer  =$b1e
BALL_SCUFFED_SHOT_VY_LO  =$40
powarc_c_X_OFFSET_BYTES  =$20
quads_v_shimmers_bitmap_addrs_lo  =$6fa8
tmarkers_c_SIZE  =$64; unused
shared_v_scoring  =$16c2
partsys_vx_lo  =$543e
trees_v_z_hi  =$a879
ball_v_mutex_drag_y_hi  =$260f; unused
maths_c_BEGIN  =$4d9c
quads_c_BEGIN  =$6601
bdrop_s_check_rotation  =$22a3
ball_v_apparent_vy_lo  =$2624
round_v_hole_filename  =$8195
trees_s_draw_foliage  =$b15d; ?
spr_s_move_up  =$e01; unused
players_v_ball_pos_x_lo  =$5668; ?
bdrop_v_spr_x_offset_lo  =$21fd
powarc_l_BITMAP_COPY_ROWS_LO  =$5e88
golfer_v_marker_index  =$3c84; ?
winslp_v_delay  =$ba3f
camera_c_BEGIN  =$3862
trees_c_NUM_PATTERNS  =$a
LPENX  =$d013; unused
zcos_hi  =$4ff9
ZP_LOADER_04  =$63; unused
SCR_CODE_K  =$b; unused
app_v_filename5  =$bf7; unused
golfer_s_update_anim  =$3d02
quads_aa_x_hi  =$682e; ?
target_base_z_hi  =$7c50
trees_s_rotate  =$afab; ?
sfx_l_BIRD2_INIT  =$89de
fmag_c_Y_MASK  =$2; ?
golfer_s_update0_hold2_animate  =$42d3; ?
round_c_SCORE_TABLE_CODE_STROKE_PLAY_FILENAME  =$8171
tmarkers_c_SHADOW_OFFSET  =$68
trees_c_SIZE  =$1109; unused
LPENY  =$d014; unused
sprd_c_GOLFER_BACKSWING_FRAMES  =$6
hole_v_boundary_left_lo  =$4632; unused
ZP_LOADER_05  =$64; unused
terrain_c_SIZE  =$38; unused
transtn_c_SIZE  =$9d; unused
SCR_CODE_J  =$a; unused
app_v_filename4  =$be8; unused
shared_v_num_players  =$1674
snd_v_data_offset  =$1cd6; unused
target_l_HAS_SHADOW  =$7c44
wash_l_SEQUENCE  =$bcc2
SP2COL  =$d029; unused
CUTLO  =$d415; unused
ZP_LOADER_06  =$65; unused
quads_s_update_shimmers  =$7a9b; ?
SCR_CODE_I  =$9; unused
quads_triangles_slope_lo  =$6e2d; ?
sc_s_calc_team_position  =$88c0; ?
ball_v_last_in_front_of_pole  =$263f
ZP_LOADER_07  =$66; unused
ball_s_calc_new_world_position  =$27fe
CAMERA_PLATE_DY_HI  =$0
hole_s_init_overhead_ball_sprite  =$47de
maths_l_FINE_COS_LO  =$4f1c
SCR_CODE_H  =$8; unused
font_c_ASCII_PLUS  =$2b
golfer_has_hit_ball  =$3c78
sc_s_calc_team_scores  =$8876; ?
SCR_CODE_DOLLAR  =$24; unused
SCR_CODE_O  =$f; unused
ball_v_is_in_water  =$2633
quads_aa_x_lo  =$67ca; ?
golfer_v_concede_query_active  =$3c8c
zcos_lo  =$4ff8
partsys_c_SPR_Y  =$bc
round_s_render_3D  =$8462; ?
target_base_z_lo  =$7c4f
golfer_s_check_concede  =$44a5
sc_v_score_str_color  =$86e1
ZP_LOADER_01  =$60; unused
hole_v_boundary_left_hi  =$4633; unused
partsys_c_SPR_X  =$a0
SCR_CODE_N  =$e; unused
golfer_l_MARKER_Y_POS  =$3b97; unused
sc_v_front9_scores  =$86d6
golfer_l_RESPONSE_OFFSET_END  =$3c73
ball_l_SPLASH_ANIM_DATA  =$25de
CUTHI  =$d416; unused
ZP_LOADER_02  =$61; unused
round_c_STATE_SHOT_IN_PROGRESS  =$0; ?
terrain_s_draw  =$a3f9; ?
SCR_CODE_M  =$d; unused
app_v_filename3  =$bdd; unused
quads_triangles_slope_hi  =$6e46; ?
round_s_check_if_must_retake_shot  =$8565; ?
hole_v_pulse_count  =$4740
ingm_s_draw_rough  =$485d
round_s_swing_or_putt  =$8380; ?
ZP_LOADER_03  =$62; unused
CAMERA_PLATE_DY_LO  =$40
powarc_c_BEGIN  =$588c
quads_final_adjustment  =$7881; ?
maths_l_FINE_COS_HI  =$4f3d
SCR_CODE_L  =$c; unused
app_v_filename2  =$bd4; unused
terrain_l_SAND_NUM_CHARS_TO_PAINT  =$a3f6
powarc_l_PUTT_ASSIST_AVG_DISTANCE_FT  =$6078
trees_s_draw  =$b002; ?
PATTERN_LO  =$23
xcos_hi  =$4ff5
SCR_CODE_C  =$3; unused
shared_c_MAX_PLAYERS  =$4
slope_l_SIN_THETA  =$2486
fmag_c_X_MASK  =$1; ?
trees_v_iter  =$af09
SCR_CODE_B  =$2; unused
ball_v_mutex_vx_hi  =$2601
ball_v_must_deflect  =$263d
hole_s_load_overhead_map  =$47c1
spr_v_vx_hi  =$c8e
shared_c_PLAYING_18_HOLES  =$0; unused
golfer_s_rotate_direction  =$4346
snd_v_RESON_buffer  =$1ce5; unused
quads_n  =$661f; ?
bmap_tiles_c_SIZE  =$0; unused
SCR_CODE_A  =$1; unused
shared_c_STROKE_PLAY  =$0; unused
ball_v_current_speed_squared_hi  =$2620
target_s_refresh_draw  =$7e59; ?
interrupts_s_do_wiping_screen  =$4b2b; ?
sfx_l_BALL_CUP_INIT  =$896e
trees_v_patterns_addr_lo  =$a4ed
partsys_land_y  =$545e
spr_v_anim_timer  =$d2e
tmarkers_c_BITMAP_DEST1  =$fc50
hole_c_PIXELS_PER_FOOT  =$7; ?
ball_s_end_shot  =$2c25; ?
SPBGCL  =$d01f; unused
bdrop_l_patterns_addr_lo  =$20c4
golfer_c_RESPONSE_NO  =$0
hole_v_boundary_top_hi  =$4631; unused
target_set_collbox  =$7e19
sstore_c_DST_BASE  =$d780
tmarkers_c_BITMAP_DEST0  =$fbe8
PATTERN_HI  =$24
ZP_LOADER_08  =$67; unused
GOLFER_POS_MARKER_SLOW_VX_LO  =$20; unused
xcos_lo  =$4ff4
playmsg_c_TYPE_PAR  =$2
maths_s_atan2  =$512a; ?
SCR_CODE_G  =$7; unused
font_s_reset_shift  =$1aeb
round_s_init  =$81a3; ?
rand_s_shuffle  =$8109; ?
ZP_LOADER_09  =$68; unused
SCR_CODE_EQUALS  =$3d; unused
dp_v_edges_iter  =$136c; unused
bdrop_v_angles  =$21ee
quads_buffer  =$6af4
SCR_CODE_F  =$6; unused
SCR_CODE_APOSTROPHE  =$27; unused
ball_v_mutex_vx_lo  =$2600
spr_v_vx_lo  =$c7e
round_v_current_ground_color  =$8194; ?
SCR_CODE_E  =$5; unused
play_l_BLANK_SPRITE_FLAG  =$cc00
bdrop_v_data_filename  =$1f2d
ball_s_update_rolling_friction  =$3263; ?
ball_v_current_speed_squared_lo  =$261f
ball_s_calc_air_drag  =$30a4; ?
trees_v_patterns_addr_hi  =$a4f7
CLUBS_STR  =$3a06
SCR_CODE_D  =$4; unused
bdrop_l_patterns_addr_hi  =$20c9
ball_s_check_stop_roll  =$2b3b; ?
hole_c_OVERHEAD_BALL_SW_SPR_NUM  =$0
powarc_c_MAX_ANIMATION_FRAME_RATE  =$5
sfx_l_BOUNCE_INIT  =$891d
trees_c_BEGIN  =$a423
golfer_l_MARKER_DELTA  =$3bf5
utils_s_comp  =$af3
hole_v_boundary_top_lo  =$4630
GREY3  =$f
shared_l_NAME_OFFSETS  =$1639; unused
interrupts_s_reset  =$4984
MULTIPLICAND  =$4
font_l_DATA  =$16c8; unused
ball_c_ROUGH_POWER_REDUCTION  =$aa
maths_mod12  =$5368; ?
CAMERA_Z_HI  =$ff
sfx_l_BROWSE_DATA  =$8917
powarc_c_SIZE  =$c35; unused
GREY2  =$c
golfer_c_SIZE  =$ad3; unused
target_s_rotate_to_pos_z_axis  =$7ce6
target_s_calc_overlapping_chars  =$7f2b; ?
SCR_CODE_Z  =$1a; unused
snd_c_BEGIN  =$1cc7; unused
golfer_c_HOLD_DURATION_SWING  =$a
playmsg_l_TYPE_OFFSETS  =$57f1
maths_mod13  =$536c; ?
GREY1  =$b
snd_c_SFX_END_CMD  =$ff; unused
wind_v_index  =$b89c; ?
bdrop_v_current_sprite_slot  =$2236
waypts_box_x0_lo  =$b717
waypts_box_z1_lo  =$b723
SCR_CODE_Y  =$19; unused
spr_c_RIGHT  =$1
shared_v_player_shirt_color_indices  =$1689
font_c_ONE_HALF  =$22; unused
golfer_s_init_putt_animation_foreswing  =$4318; ?
sfx_l_SPLASH_DATA  =$8999
maths_mod10  =$534a; ?
_DEBUG_PHYSICS_VARS_  =$0
ball_v_spin_axis_z_hi  =$2656
clubs_l_DISTANCE_PIXELS_HI  =$3a74
GOLFER_POS_Y_UPPER  =$be; unused
partsys_x_hi  =$5426
SFX_INIT_ADDRS_ZP_LO  =$58
SCR_CODE_X  =$18; unused
spr_s_write_to_vic_ii  =$ef0
ball_v_is_in_trees  =$2632
slope_c_DELAY  =$5
maths_mod11  =$534e; ?
winslp_v_final_vz_lo  =$ba3d; ?
IRQMSK  =$d01a
YELLOW  =$7
powarc_v_precision_offset  =$6095; ?
round_s_handle_team_concede_hole  =$8632; ?
font_v_draw_modify  =$1a91; unused
CAMERA_Z_LO  =$67
clubs_s_draw2  =$3aba
shared_v_player_skin_tones  =$1685
dp_l_BITMAP_MASKS  =$1270; unused
shared_v_player_genders  =$167d
golfer_l_MARKER_X_POS  =$3b8a; unused
partsys_l_BASE_VY_LO  =$53f7
round_s_prepare_loading_msg  =$840d
quads_buf2_min_z_i  =$6ea7
winslp_s_calc_final_vector  =$bb46; ?
ball_c_STATE_ROLLING  =$3
round_s_record_msg  =$8615; ?
golfer_c_STATE_IN_LIMBO  =$e
golfer_s_draw  =$3c91
trees_c_PATTERNS_BLOCK_SIZE  =$200
waypts_box_x0_hi  =$b719
waypts_box_z1_hi  =$b725
players_c_BEGIN  =$564c
quads_buffer_size  =$6b10
maths_mod14  =$5370; ?
stats_s_clear_balls_holed  =$a35a; ?
VMCSB  =$d018; unused
ball_v_spin_axis_z_lo  =$2655
clubs_l_DISTANCE_PIXELS_LO  =$3a68
golfer_v_shot_power  =$3c7a
partsys_x_lo  =$541e
SFX_INIT_ADDRS_ZP_HI  =$59
maths_mod15  =$5374; ?
ball_v_splash_anim_base_sw_sprite  =$2668
winslp_v_final_vz_hi  =$ba3e; ?
SCR_CODE_S  =$13; unused
SCR_CODE_STAR  =$2a; unused
gfxs_c_BANK1  =$2; unused
bdrop_l_SPRITE_POSITIONS_X_LO  =$1e95
clubs_s_set_min_allowed  =$3b37
sfx_l_BIRD1_INIT  =$89ca
fmag_c_Z_MASK  =$4; ?
quads_find_minmax_z  =$7104
SCR_CODE_R  =$12; unused
gfxs_c_BANK0  =$3; unused
BALL_SCUFFED_SHOT_VX_HI  =$0
wind_l_INDICATOR_BYTES_INDICES  =$b882
clubs_reset  =$3a89; unused
stats_s_clear_text_row1  =$a224; ?
ball_v_z_pos_rel_to_hole_old  =$266a
partsys_vy_hi  =$5456
SCR_CODE_Q  =$11; unused
gfxs_c_BANK3  =$0; unused
font_c_NOP_OPCODE  =$ea; unused
play_l_MAX_STR_SPRITE  =$d740
ball_v_mutex_drag_x_lo  =$260c
golfer_s_check_power_speed  =$4581; ?
golfer_c_RESPONSE_HIGHLIGHT_COLOR  =$7
GOLFER_BASE_Y  =$be
golfer_c_STATE_ANIMATE_HOLD2  =$9
trees_l_COLOR_PATTERNS  =$a4b3
ball_v_apparent_vx_hi  =$2623
POWARC_COPY_HI  =$3e
msg_c_BEGIN  =$1c0a; unused
SCR_CODE_P  =$10; unused
gfxs_c_BANK2  =$1; unused
GOLFER_BASE_X  =$98
hole_c_BEGIN  =$462a
sprd_c_GOLFER_SWING_LOWER  =$6e
shared_l_TEAM_NAME_ADDR_HI  =$1648
quads_find_minmax_y  =$7523; ?
SPMC1  =$d026
SCR_CODE_W  =$17; unused
bdrop_l_SPRITE_POSITIONS_X_HI  =$1eae
ball_v_spr_x_parity  =$2637
quads_s_spawn_new_shimmer  =$7a5e
target_s_reset  =$7d73
trees_v_extra_height  =$af0f
SPMC0  =$d025
SCR_CODE_V  =$16; unused
joy_c_PORT2  =$0
spr_v_hires  =$dbe
BALL_SCUFFED_SHOT_VX_LO  =$30
powarc_s_toggle_punch  =$648e; ?
partsys_vy_lo  =$544e
SCR_CODE_U  =$15; unused
joy_c_PORT1  =$1; unused
gfxs_c_PAGES  =$2; unused
ball_v_mutex_drag_x_hi  =$260d
ball_v_apparent_vx_lo  =$2622
POWARC_COPY_LO  =$3d
target_s_check_if_behind_trunk  =$7e62; ?
SCR_CODE_T  =$14; unused
shared_l_PLAYER_HAIR_COLORS  =$1631
shared_c_MALE  =$0; unused
snd_s_kill_all  =$1e31; unused
playmsg_c_SIZE  =$10a; unused
shared_l_TEAM_NAME_ADDR_LO  =$1646
target_s_recalculate_aa_coords  =$7d17
