spr_c_UP  =$2; unused
spr_c_DOWN  =$3; unused
snd_c_FILTER_HIGHPASS  =$40; unused
LINE_X1_LO  =$2b
SP5COL  =$d02c; unused
ORANGE  =$8; unused
spr_s_clear_all_expands  =$f84; unused
shared_v_team_names_offsets_begin  =$16b7; unused
R6510  =$1
SPENA  =$d015; unused
font_s_draw_text_direct  =$1a7c; unused
RASTER  =$d012; unused
shared_c_PLAYING_FRONT_9  =$1; unused
font_s_draw_text  =$1a5a
spr_s_hide_all  =$f8f; unused
font_c_ASCII_SPACE  =$20
CB_LOADFILE_EXOMIZER  =$5c5
sprd_c_GOLFER_PUTT_LOWER  =$69; unused
SPSPCL  =$d01e; unused
VCREG2  =$d40b
msg_c_LOADING_SCORE_CARDS  =$1; unused
VCREG3  =$d412
SCR_CODE_BANG  =$21; unused
ZP_END  =$6c; unused
spr_v_color  =$d7e
spr_v_is_next_frame  =$dd0
VCREG1  =$d404
ZSIN_LO  =$18; unused
PUTT_ASSIST_DEST_ZP_HI  =$5f; unused
LINE_Y1_LO  =$2c
dp_s_draw_pixel  =$136f
gfxs_s_init  =$b2e; ?
spr_c_LEFT  =$0; unused
shared_v_is_match_play  =$16c2; unused
spr_v_dx  =$d5e
app_s_run_prelude  =$c20; ?
spr_v_dy  =$d6e
shared_v_team_membership  =$16bb; unused
BIT_ZEROPAGE  =$24; unused
ZSIN_HI  =$19; unused
PUTT_ASSIST_DEST_ZP_LO  =$5e; unused
joy_c_UP  =$1
font_c_ASCII_MINUS  =$2d; unused
MSIGX  =$d010
BLACK  =$0
shared_v_wind_difficulty  =$16c6; unused
P0  =$2
XSIN_LO  =$14; unused
SND_CH3_DATA_ZP_LO  =$52; unused
P1  =$3
SCR_CODE_OPEN_BRACKET  =$1b; unused
P2  =$4
CURSOR_POS_SR_HI  =$4d; unused
SCR_CODE_HUH  =$3f; unused
shared_v_sand_traps_difficulty  =$16c4; unused
snd_s_next_free_channel  =$1d0f; ?
P3  =$5
P4  =$6
XSIN_HI  =$15; unused
SND_CH3_DATA_ZP_HI  =$53; unused
shared_l_PLAYER_SHIRT_COLORS  =$1633; unused
P5  =$7
EXTCOL  =$d020
P6  =$8
CURSOR_POS_SR_LO  =$4c; unused
P7  =$9
spr_v_direction_x  =$cde; unused
COLOR_RAM  =$d800
LINE_X0_LO  =$29
SCR_CODE_AT  =$0; unused
spr_v_direction_y  =$cee; unused
EDGES_LO  =$2d
SP4COL  =$d02b; unused
HIBASE  =$288; unused
SCR_CODE_GT  =$3e; unused
SHFLAG  =$28d; unused
sprd_c_GOLFER_WATCHING_SWING_UPPER  =$6d; unused
LIGHT_BLUE  =$e
spr_c_VISIBLE_ALL_T  =$32; unused
end_of_core  =$1e6c; ?
snd_s_update  =$1d9c; unused
EDGES_HI  =$2e; unused
utils_s_16bit_hex_to_dec  =$a7c; unused
gfxs_c_BITMAP_OFFSET  =$8
spr_c_VISIBLE_ALL_R  =$40; unused
sprd_c_GOLFER_PUTT_FORESWING_FRAMES_PT1  =$3; unused
SETLFS  =$ffba; unused
sprd_c_GOLFER_PUTT_FORESWING_FRAMES_PT0  =$4; unused
sprd_c_GOLFER_CONTACT_OFFSET  =$9; unused
font_c_ASCII_0  =$30; ?
VIOLET  =$4
SCR_CODE_SEMICOLON  =$3b; unused
KB_MATRIX_DECODE_TBL  =$eb81; unused
gfxs_s_clear_msg_area  =$b9c; unused
spr_s_animate_onetime  =$e7b; unused
msg_s_clear  =$1c9f; ?
snd_c_OSC_OFF_CMD  =$fd
app_s_run  =$c02; ?
utils_s_bubble_sort  =$acf; unused
gfxs_c_CHARS_TO  =$c000
SCR_CODE_UP  =$1e; unused
joy_c_RIGHT  =$8
shared_v_player_joysticks  =$1681; unused
utils_l_EOR_BIT_LOOKUP  =$a6e
LINE_Y0_LO  =$2a
SCR_CODE_SPACE  =$20
spr_s_move_right  =$dee; unused
msg_s_display  =$1c6a; unused
msg_s_display_at_column  =$1c71; unused
sprd_c_PARTICLES_SHOT  =$31; unused
spr_c_VISIBLE_ALL_B  =$e5; unused
snd_v_counter  =$1cd3
FREHI1  =$d401; unused
FRELO3  =$d40e; unused
SND_CH2_DATA_ZP_LO  =$50; unused
BIT_ABSOLUTE  =$2c; unused
FRELO2  =$d407; unused
SETNAM  =$ffbd; unused
joy_v_fire_locked  =$9e5
FRELO1  =$d400
FREHI3  =$d40f; unused
FREHI2  =$d408; unused
spr_c_VISIBLE_ALL_L  =$18; unused
SP4X  =$d008; unused
SP6Y  =$d00d; unused
SND_CH2_DATA_ZP_HI  =$51; unused
joy_v_right_locked  =$9e3
SP4Y  =$d009; unused
SP6X  =$d00c; unused
SP0X  =$d000
SP2Y  =$d005; unused
SCR_CODE_OPEN_PAREN  =$28; unused
SP0Y  =$d001; unused
SP2X  =$d004; unused
gfxs_c_CHARS_OFFSET  =$0; unused
WHITE  =$1
SP7COL  =$d02e; unused
app_s_run_finale  =$c43; ?
PARTSYS_HI  =$34; unused
SCR_CODE_CLOSE_BRACKET  =$1d; unused
PARTSYS_LO  =$33; unused
SCROLY  =$d011; unused
LIGHT_GREEN  =$d; unused
sprd_c_PARTICLES_SPLASH  =$32; unused
sprd_c_GOLFER_SWING_UPPER  =$5f; unused
SCROLX  =$d016; unused
snd_v_waiting_to_end  =$1ccd
shared_l_NAME_ADDR_HI  =$1642; unused
CINV  =$314; unused
TREES_LO  =$1b
BITMAP_LO  =$21
SCR_CODE_DASH  =$2d; unused
shared_c_NUM_COURSES  =$6; unused
snd_c_NUM_CHANNELS  =$3
SCNKEY  =$ff9f; unused
shared_l_NAME_ADDR_LO  =$163e; unused
msg_c_FISHING  =$2; unused
TREES_HI  =$1c
SCR_CODE_CLOSE_PAREN  =$29; unused
joy_s_is_vertical  =$9f6; unused
BITMAP_HI  =$22
msg_l_MSG_ADDR_HI  =$1c5f
shared_c_PLAYING_BACK_9  =$2; unused
ZCOS_LO  =$16; unused
spr_v_vx_count  =$cbe
joy_v_current_port  =$9e7; unused
msg_c_ROW  =$c0
msg_l_MSG_ADDR_LO  =$1c5a
ZCOS_HI  =$17; unused
spr_v_vy_count  =$cce
shared_v_holes  =$16c3; unused
BROWN  =$9
SND_CH1_DATA_ZP_LO  =$4e; unused
app_s_run_play  =$c2d; ?
dp_l_BITMAP_ROWS_LO  =$fa0
font_c_ASCII_A  =$41; unused
INTERRUPTS_LO  =$3f; unused
dp_s_set_color_ram_cell  =$156a; unused
dp_l_BYTE_PATTERNS  =$1284; unused
_DEBUG_TEST_HOLE_  =$0; unused
XCOS_LO  =$12; unused
shared_l_PLAYER_SKIN_TONES  =$162f; unused
shared_v_team_lens  =$16bf; unused
SND_CH1_DATA_ZP_HI  =$4f; unused
dp_l_BITMAP_ROWS_HI  =$1068
shared_c_MAX_NAME_LEN  =$a
LIGHT_RED  =$a
INTERRUPTS_HI  =$40; unused
XCOS_HI  =$13; unused
SCR_CODE_POUND  =$1c; unused
spr_c_OFFSCREEN_R  =$58; unused
spr_s_clear_msb_all  =$ee2; unused
SP6COL  =$d02d; unused
COLORS_HI  =$28; unused
snd_v_channel_active  =$1cd0
VICIRQ  =$d019; unused
ZP_LOADER_10  =$69; unused
ZP_LOADER_11  =$6a; unused
dp_s_draw_string  =$15c7; unused
ZP_LOADER_12  =$6b; unused
spr_c_OFFSCREEN_T  =$1d; unused
sprd_c_LOADABLE_BASE  =$5e
D6510  =$0; unused
COLORS_LO  =$27; unused
SCR_CODE_AMPERSAND  =$26; unused
PWHI1  =$d403; unused
PWLO3  =$d410; unused
SFX_DATA_ADDRS_ZP_HI  =$5b; unused
PWLO2  =$d409; unused
PWLO1  =$d402; unused
POWARC_LO  =$39; unused
msg_c_WAIT_STR  =$1c4c
PWHI3  =$d411; unused
PWHI2  =$d40a; unused
_DEBUG_APEX_  =$0; unused
SFX_DATA_ADDRS_ZP_LO  =$5a
gfxs_c_DISPLAY_OFFSET  =$20
POWARC_HI  =$3a; unused
dp_l_BITMAP_PATTERNS  =$1274
SCR_CODE_PERIOD  =$2e; unused
spr_c_OFFSCREEN_B  =$fa; unused
sprd_c_GOLFER_PUTT_CONTACT_OFFSET  =$7; unused
RED  =$2
VM_LO  =$25; unused
dp_l_COLOR_RAM_ROWS_HI  =$12a1
dp_s_draw_line  =$13d8; unused
utils_l_BIT_LOOKUP  =$a66
spr_animate_loop  =$ea8; unused
sprd_c_GOLFER_SWING_CLUB  =$35; unused
sprd_c_GOLFER_PUTT_BACKSWING_FRAMES  =$4; unused
spr_v_edge  =$dcf
YXPAND  =$d017
dp_l_COLOR_RAM_ROWS_LO  =$1288
VM_HI  =$26; unused
spr_s_calc_dx  =$e25; unused
spr_s_calc_dy  =$e3b; unused
MATHS7  =$11; unused
MATHS6  =$10; unused
MATHS5  =$f
MATHS4  =$e
SPBGPR  =$d01b
MATHS3  =$d
CAMERA3  =$20; unused
utils_v_dec_digits  =$a76
MATHS2  =$c
CAMERA2  =$1f; unused
XXPAND  =$d01d
CAMERA1  =$1e; unused
spr_c_OFFSCREEN_L  =$0; unused
MATHS1  =$b
font_s_prepare_colors  =$1aaf; unused
MATHS0  =$a
CAMERA0  =$1d; unused
kbmat_c_J  =$22; unused
shared_c_MATCH_PLAY  =$1; unused
SFDX  =$cb; unused
kbmat_c_K  =$25; unused
joy_v_up_locked  =$9dd
spr_s_clamp_right  =$e65; unused
SP1COL  =$d028; unused
sprd_c_GOLFER_MIDSWING_OFFSET  =$5; unused
kbmat_c_H  =$1d; unused
GREEN  =$5
WS_X_HI  =$30; unused
kbmat_c_I  =$21; unused
kbmat_c_N  =$27; unused
kbmat_c_O  =$26; unused
joy_c_DOWN  =$2
kbmat_c_L  =$2a; unused
WS_X_LO  =$2f; unused
kbmat_c_M  =$24; unused
ATDCY3  =$d413; unused
joy_v_left_locked  =$9e1
shared_c_MAX_TEAM_NAME_LEN  =$15
kbmat_c_B  =$1c; unused
dp_s_build_mask  =$159a; unused
ATDCY2  =$d40c; unused
BALL_TRI_X_HI  =$36; unused
kbmat_c_C  =$14; unused
utils_s_ror_two_bits  =$b15; unused
shared_v_greens_difficulty  =$16c5; unused
ATDCY1  =$d405; unused
kbmat_c_A  =$a; unused
shared_l_CHARS_FOR_SCORE_ZERO  =$164a; unused
snd_v_data_address_lo  =$1cdf
snd_s_clear_all  =$1e46; unused
snd_s_set_max_volume  =$1ce7; unused
kbmat_c_F  =$15; unused
BALL_TRI_X_LO  =$35; unused
shared_v_player_name_indices  =$1679; unused
kbmat_c_G  =$1a; unused
gfxs_c_SPR_PTR_BASE  =$cbf8
kbmat_c_D  =$12; unused
kbmat_c_E  =$e; unused
snd_v_data_address_hi  =$1ce2
snd_v_SIGVOL_buffer  =$1ce6
kbmat_c_Z  =$c; unused
SCR_CODE_9  =$39; unused
gfxs_c_DISPLAY_BASE  =$c800
kbmat_c_X  =$17; unused
CURSOR_POS_HI  =$4b; unused
SCR_CODE_8  =$38; unused
kbmat_c_Y  =$19; unused
end_of_loader  =$9c6; unused
spr_v_x_hi  =$c5e
joy_c_LEFT  =$4
snd_v_gates  =$1cdc
SCR_CODE_PLUS  =$2b; unused
sprd_c_GOLFER_PUTT_CLUB  =$43; unused
app_s_run_nineteenth  =$c38; ?
shared_c_NUM_SHIRT_COLORS  =$6; unused
CURSOR_POS_LO  =$4a; unused
spr_v_x_lo  =$c4e
SIGVOL  =$d418
SCR_CODE_3  =$33; unused
kbmat_c_R  =$11; unused
SCR_CODE_2  =$32; unused
kbmat_c_S  =$d; unused
SCR_CODE_1  =$31; unused
spr_v_fg_priority  =$dce; unused
kbmat_c_P  =$29; unused
SPMC  =$d01c
SND_REGS_BASE_ZP_LO  =$56
SCR_CODE_0  =$30; unused
spr_v_bg_priority  =$dae
kbmat_c_Q  =$3e; unused
SCR_CODE_7  =$37; unused
kbmat_c_V  =$1f; unused
icon_s_draw  =$1af6; unused
SCR_CODE_6  =$36; unused
SCR_CODE_COLON  =$3a; unused
kbmat_c_W  =$9; unused
SCR_CODE_5  =$35; unused
kbmat_c_T  =$16; unused
SND_REGS_BASE_ZP_HI  =$57
SCR_CODE_4  =$34; unused
dp_s_set_video_ram_cell  =$1582; unused
font_s_shift_text_right  =$1adf; unused
kbmat_c_U  =$1e; unused
sprd_c_GOLFER_WATCHING_SWING_CLUB  =$4d; unused
SP0COL  =$d027
FADE_CR_SRC_LO  =$46; unused
msg_c_FISHING_STR  =$1c2b
kbmat_c_RUNSTOP  =$3f; unused
RANDOM_X_TMP  =$41; unused
shared_c_FEMALE  =$1; unused
FADE_CR_SRC_HI  =$47; unused
SCR_CODE_LT  =$3c; unused
utils_c_HEX2DEC_RESULT_SIZE_BYTES  =$5
sprd_c_GOLFER_PUTT_LOOKING_UP  =$5e; unused
sprd_c_GOLFER_PUTT_MIDSWING_OFFSET  =$4; unused
dp_l_BITMAP_COLS_HI  =$11d0
SCR_CODE_PERCENT  =$25; unused
joy_v_down_locked  =$9df
dp_l_CHARS_LO  =$12ec
msg_c_CONCEDE_STR  =$1c38
app_v_filename  =$bc8
snd_v_must_loop  =$1cd9
dp_l_BITMAP_COLS_LO  =$1130
gfxs_s_init_colors  =$b6d; unused
dp_l_CHARS_HI  =$132c
msg_v_last_len  =$1c69
RESON  =$d417
SND_INIT_DATA_ZP_LO  =$54
SCR_CODE_DOUBLE_QUOTE  =$22; unused
FADE_SR_SRC_LO  =$48; unused
gfxs_c_BITMAP_BASE  =$e000
shared_v_course_index  =$16c1; unused
CI2PRA  =$dd00
BLUE  =$6
sprd_c_CROSSHAIR  =$4e; unused
gfxs_c_COLOR_RAM_OFFSET  =$1000; unused
shared_v_team_names  =$168d; ?
SND_INIT_DATA_ZP_HI  =$55
joy_s_release_all_locks  =$a04; unused
FADE_SR_SRC_HI  =$49; unused
msg_l_MSG_LENGTHS  =$1c64
SCR_CODE_SLASH  =$2f; unused
spr_s_clamp_left  =$e51; unused
sprd_c_GOLFER_PUTT_UPPER  =$5f; unused
shared_v_player_names  =$164c; ?
msg_c_OUT_OF_BOUNDS  =$0; unused
sprd_c_GOLFER_FORESWING_FRAMES  =$9; unused
app_s_run_splash  =$c15; ?
spr_c_CURRENT_CHAR_ZP_LO  =$3b; unused
font_l_CHAR_DATA_HI  =$19db
dp_s_draw_byte  =$13b4; unused
msg_c_CONCEDE_HOLE  =$3; unused
SP5X  =$d00a; unused
SP7Y  =$d00f; unused
CB_LOADFILE  =$59c; unused
snd_c_FILTER_BANDPASS  =$20; unused
SP5Y  =$d00b; unused
SP7X  =$d00e; unused
MEMSIZ  =$37; unused
spr_c_CURRENT_CHAR_ZP_HI  =$3c; unused
snd_s_real_init  =$1d1a; ?
font_l_CHAR_DATA_LO  =$1980
SP1X  =$d002; unused
SP3Y  =$d007; unused
LOAD  =$ffd5; unused
SP1Y  =$d003; unused
SP3X  =$d006; unused
sprd_c_BALL  =$33; unused
SUREL2  =$d40d; unused
FADE_SR_HI  =$45; unused
dp_s_record_edge  =$155f; ?
SUREL3  =$d414; unused
FADE_CR_HI  =$43; unused
joy_s_is_horizontal  =$9e8; unused
dp_c_BITMAP_START  =$e000
SP3COL  =$d02a; unused
SUREL1  =$d406; unused
WS_Z_HI  =$32; unused
utils_l_HEX2DEC_LOOKUP  =$a16
spr_v_framerate  =$d3e
FADE_SR_LO  =$44; unused
spr_v_anim_start_ptr  =$cfe
spr_v_xxpand  =$d9e
FADE_CR_LO  =$42; unused
spr_v_current_ptr  =$d4e
msg_s_display_stock_msg  =$1c7e; unused
WS_Z_LO  =$31; unused
spr_s_move_down  =$e13; unused
font_l_SHIFT_RIGHT_BYTES  =$1a56
BGCOL3  =$d024; unused
C2DDRA  =$dd02
msg_c_SIZE  =$bd; unused
BGCOL2  =$d023; unused
BALL_TRI_Z_HI  =$38; unused
spr_v_y  =$c6e
snd_c_FILTER_LOWPASS  =$10; unused
spr_v_vy_hi  =$cae
BGCOL1  =$d022; unused
dp_l_VIDEO_RAM_ROWS_HI  =$12d3
gfxs_s_clear_bitmap  =$b4b; ?
BGCOL0  =$d021
POWARC_FILL_SRC_ITER_HI  =$3c; unused
PUTT_ASSIST_SRC_ZP_HI  =$5d; unused
sprd_c_GOLFER_LOOKING_UP  =$5e; unused
spr_v_yxpand  =$d8e
msg_c_OUT_OF_BOUNDS_STR  =$1c0a
BALL_TRI_Z_LO  =$37; unused
SCR_CODE_HASH  =$23; unused
joy_c_FIRE  =$10; unused
spr_v_vy_lo  =$c9e
SIGN_CHANGED  =$1a; unused
spr_s_sync_msb  =$ec7; unused
dp_l_VIDEO_RAM_ROWS_LO  =$12ba
POWARC_FILL_SRC_ITER_LO  =$3b; unused
PUTT_ASSIST_SRC_ZP_LO  =$5c; unused
CYAN  =$3; unused
snd_l_REGS_BASE_ADDR_LO  =$1cc7
spr_v_anim_seq_inc  =$d1e
msg_c_WAIT  =$4; unused
SCR_CODE_COMMA  =$2c; unused
shared_v_random_seed  =$16c7; unused
snd_l_REGS_BASE_ADDR_HI  =$1cca
sprd_c_BALL_SHADOW  =$34; unused
spr_s_move_left  =$dd1; unused
spr_v_anim_end_ptr  =$d0e
shared_v_player_name_lens  =$1675; unused
CIAPRA  =$dc00
SCR_CODE_LEFT  =$1f; unused
snd_s_init_sfx  =$1cf0; unused
msg_c_SCORE_CARDS_STR  =$1c18
snd_c_SIZE  =$1a5; unused
CB_INITLOADER  =$3000
utils_s_write_digits_to_buffer  =$b1e; unused
shared_v_scoring  =$16c2
spr_s_move_up  =$e01; unused
LPENX  =$d013; unused
ZP_LOADER_04  =$63; unused
SCR_CODE_K  =$b; unused
app_v_filename5  =$bf7
LPENY  =$d014; unused
sprd_c_GOLFER_BACKSWING_FRAMES  =$6; unused
ZP_LOADER_05  =$64; unused
SCR_CODE_J  =$a; unused
app_v_filename4  =$be8
shared_v_num_players  =$1674; unused
snd_v_data_offset  =$1cd6
SP2COL  =$d029; unused
CUTLO  =$d415
ZP_LOADER_06  =$65; unused
SCR_CODE_I  =$9; unused
ZP_LOADER_07  =$66; unused
SCR_CODE_H  =$8; unused
font_c_ASCII_PLUS  =$2b; unused
SCR_CODE_DOLLAR  =$24; unused
SCR_CODE_O  =$f; unused
ZP_LOADER_01  =$60; unused
SCR_CODE_N  =$e; unused
CUTHI  =$d416
ZP_LOADER_02  =$61; unused
SCR_CODE_M  =$d; unused
app_v_filename3  =$bdd
ZP_LOADER_03  =$62; unused
SCR_CODE_L  =$c; unused
app_v_filename2  =$bd4
PATTERN_LO  =$23
SCR_CODE_C  =$3; unused
shared_c_MAX_PLAYERS  =$4
SCR_CODE_B  =$2; unused
spr_v_vx_hi  =$c8e
shared_c_PLAYING_18_HOLES  =$0; unused
snd_v_RESON_buffer  =$1ce5
SCR_CODE_A  =$1; unused
shared_c_STROKE_PLAY  =$0; unused
spr_v_anim_timer  =$d2e
SPBGCL  =$d01f; unused
PATTERN_HI  =$24
ZP_LOADER_08  =$67; unused
SCR_CODE_G  =$7; unused
font_s_reset_shift  =$1aeb; unused
ZP_LOADER_09  =$68; unused
SCR_CODE_EQUALS  =$3d
dp_v_edges_iter  =$136c
SCR_CODE_F  =$6; unused
SCR_CODE_APOSTROPHE  =$27; unused
spr_v_vx_lo  =$c7e
SCR_CODE_E  =$5; unused
SCR_CODE_D  =$4; unused
utils_s_comp  =$af3; unused
GREY3  =$f
shared_l_NAME_OFFSETS  =$1639; unused
font_l_DATA  =$16c8
GREY2  =$c
SCR_CODE_Z  =$1a; unused
snd_c_BEGIN  =$1cc7
GREY1  =$b; unused
snd_c_SFX_END_CMD  =$ff
SCR_CODE_Y  =$19; unused
spr_c_RIGHT  =$1; unused
shared_v_player_shirt_color_indices  =$1689; unused
font_c_ONE_HALF  =$22; unused
_DEBUG_PHYSICS_VARS_  =$0; unused
SFX_INIT_ADDRS_ZP_LO  =$58
SCR_CODE_X  =$18; unused
spr_s_write_to_vic_ii  =$ef0; unused
IRQMSK  =$d01a; unused
YELLOW  =$7
font_v_draw_modify  =$1a91
shared_v_player_skin_tones  =$1685; unused
dp_l_BITMAP_MASKS  =$1270
shared_v_player_genders  =$167d; unused
VMCSB  =$d018
SFX_INIT_ADDRS_ZP_HI  =$59; unused
SCR_CODE_S  =$13; unused
SCR_CODE_STAR  =$2a; unused
gfxs_c_BANK1  =$2; unused
SCR_CODE_R  =$12; unused
gfxs_c_BANK0  =$3; unused
SCR_CODE_Q  =$11; unused
gfxs_c_BANK3  =$0
font_c_NOP_OPCODE  =$ea
POWARC_COPY_HI  =$3e; unused
msg_c_BEGIN  =$1c0a
SCR_CODE_P  =$10; unused
gfxs_c_BANK2  =$1; unused
sprd_c_GOLFER_SWING_LOWER  =$6e; unused
shared_l_TEAM_NAME_ADDR_HI  =$1648; unused
SPMC1  =$d026; unused
SCR_CODE_W  =$17; unused
SPMC0  =$d025; unused
SCR_CODE_V  =$16; unused
joy_c_PORT2  =$0
spr_v_hires  =$dbe
SCR_CODE_U  =$15; unused
joy_c_PORT1  =$1; unused
gfxs_c_PAGES  =$2; unused
POWARC_COPY_LO  =$3d; unused
SCR_CODE_T  =$14; unused
shared_l_PLAYER_HAIR_COLORS  =$1631; unused
shared_c_MALE  =$0; unused
snd_s_kill_all  =$1e31; unused
shared_l_TEAM_NAME_ADDR_LO  =$1646; unused
